/*
 *
 * The following tables are derived from National Instruments examples
 * under their Copyright:
 *
 * Copyright (c) 2006, National Instruments Corporation
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of National Instruments Corporation nor the names of its
 *    contributors may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 *  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 *  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 *  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 *  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 *  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 *  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 *
 */

#define AI_Command_1__AI_CONVERT_Pulse                                0x0   ,  0xfffe    
#define AI_Command_1__AI_LOCALMUX_CLK_Pulse                           0x2   ,  0xfffb    
#define AI_Command_1__AI_EXTMUX_CLK_Pulse                             0x3   ,  0xfff7    
#define AI_Command_1__AI_SCAN_IN_PROG_Pulse                           0x4   ,  0xffef    
#define AI_Command_1__AI_SC_Load                                      0x5   ,  0xffdf    
#define AI_Command_1__AI_SC_Arm                                       0x6   ,  0xffbf    
#define AI_Command_1__AI_DIV_Load                                     0x7   ,  0xff7f    
#define AI_Command_1__AI_DIV_Arm                                      0x8   ,  0xfeff    
#define AI_Command_1__AI_SI_Load                                      0x9   ,  0xfdff    
#define AI_Command_1__AI_SI_Arm                                       0xa   ,  0xfbff    
#define AI_Command_1__AI_SI2_Load                                     0xb   ,  0xf7ff    
#define AI_Command_1__AI_SI2_Arm                                      0xc   ,  0xefff    
#define AI_Command_1__AI_Disarm                                       0xd   ,  0xdfff    
#define AI_Command_1__AI_Analog_Trigger_Reset                         0xe   ,  0xbfff    
#define AI_Command_2__AI_START1_Pulse                                 0x0   ,  0xfffe    
#define AI_Command_2__AI_START2_Pulse                                 0x1   ,  0xfffd    
#define AI_Command_2__AI_START_Pulse                                  0x2   ,  0xfffb    
#define AI_Command_2__AI_STOP_Pulse                                   0x3   ,  0xfff7    
#define AI_Command_2__AI_SC_Switch_Load_On_TC                         0x4   ,  0xffef    
#define AI_Command_2__AI_SI_Switch_Load_On_TC                         0x7   ,  0xff7f    
#define AI_Command_2__AI_SI_Switch_Load_On_STOP                       0x8   ,  0xfeff    
#define AI_Command_2__AI_SI_Switch_Load_On_SC_TC                      0x9   ,  0xfdff    
#define AI_Command_2__AI_SC_Save_Trace                                0xa   ,  0xfbff    
#define AI_Command_2__AI_START1_Disable                               0xb   ,  0xf7ff    
#define AI_Command_2__AI_End_On_End_Of_Scan                           0xe   ,  0xbfff    
#define AI_Command_2__AI_End_On_SC_TC                                 0xf   ,  0x7fff    
#define AI_Mode_2__AI_SC_Write_Switch                                 0x0   ,  0xfffe    
#define AI_Mode_2__AI_SC_Reload_Mode                                  0x1   ,  0xfffd    
#define AI_Mode_2__AI_SC_Initial_Load_Source                          0x2   ,  0xfffb    
#define AI_Mode_2__AI_SI_Write_Switch                                 0x3   ,  0xfff7    
#define AI_Mode_2__AI_SI_Reload_Mode                                  0x4   ,  0xff8f    
#define AI_Mode_2__AI_SI_Initial_Load_Source                          0x7   ,  0xff7f    
#define AI_Mode_2__AI_SI2_Reload_Mode                                 0x8   ,  0xfeff    
#define AI_Mode_2__AI_SI2_Initial_Load_Source                         0x9   ,  0xfdff    
#define AI_Mode_2__AI_External_MUX_Present                            0xc   ,  0xefff    
#define AI_Mode_2__AI_Pre_Trigger                                     0xd   ,  0xdfff    
#define AI_Mode_2__AI_Start_Stop_Gate_Enable                          0xe   ,  0xbfff    
#define AI_Mode_2__AI_SC_Gate_Enable                                  0xf   ,  0x7fff    
#define AI_Mode_3__AI_External_Gate_Select                            0x0   ,  0xffe0    
#define AI_Mode_3__AI_External_Gate_Polarity                          0x5   ,  0xffdf    
#define AI_Mode_3__AI_FIFO_Mode                                       0x6   ,  0xff3f    
#define AI_Mode_3__AI_External_Gate_Mode                              0x8   ,  0xfeff    
#define AI_Mode_3__AI_Delayed_START1                                  0x9   ,  0xfdff    
#define AI_Mode_3__AI_Delayed_START2                                  0xa   ,  0xfbff    
#define AI_Mode_3__AI_SI2_Source_Select                               0xb   ,  0xf7ff    
#define AI_Mode_3__AI_Software_Gate                                   0xd   ,  0xdfff    
#define AI_Mode_3__AI_Delay_START                                     0xe   ,  0xbfff    
#define AI_Mode_3__AI_Trigger_Length                                  0xf   ,  0x7fff    
#define AI_Personal__AI_EXTMUX_CLK_Pulse_Width                        0x6   ,  0xffbf    
#define AI_Personal__AI_CONVERT_Pulse_Width                           0xa   ,  0xfbff    
#define AI_Output_Control__AI_CONVERT_Output_Select                   0x0   ,  0xfffc    
#define AI_Output_Control__AI_EXTMUX_CLK_Output_Select                0x6   ,  0xff3f    
#define AI_Output_Control__AI_SCAN_IN_PROG_Output_Select              0x8   ,  0xfcff    
#define AI_Output_Control__AI_START_Output_Select                     0xa   ,  0xfbff    
#define AI_START_STOP_Select__AI_START_Select                         0x0   ,  0xffe0    
#define AI_START_STOP_Select__AI_START_Edge                           0x5   ,  0xffdf    
#define AI_START_STOP_Select__AI_START_Sync                           0x6   ,  0xffbf    
#define AI_START_STOP_Select__AI_STOP_Select                          0x7   ,  0xf07f    
#define AI_START_STOP_Select__AI_STOP_Edge                            0xc   ,  0xefff    
#define AI_START_STOP_Select__AI_STOP_Sync                            0xd   ,  0xdfff    
#define AI_START_STOP_Select__AI_STOP_Polarity                        0xe   ,  0xbfff    
#define AI_START_STOP_Select__AI_START_Polarity                       0xf   ,  0x7fff    
#define AI_Status_1__Pass_Thru_0_Interrupt_St                         0x0   ,  0xfffe    
#define AI_Status_1__AI_FIFO_Request_St                               0x1   ,  0xfffd    
#define AI_Status_1__G0_Gate_Interrupt_St                             0x2   ,  0xfffb    
#define AI_Status_1__G0_TC_St                                         0x3   ,  0xfff7    
#define AI_Status_1__AI_STOP_St                                       0x4   ,  0xffef    
#define AI_Status_1__AI_START_St                                      0x5   ,  0xffdf    
#define AI_Status_1__AI_SC_TC_St                                      0x6   ,  0xffbf    
#define AI_Status_1__AI_START1_St                                     0x7   ,  0xff7f    
#define AI_Status_1__AI_START2_St                                     0x8   ,  0xfeff    
#define AI_Status_1__AI_SC_TC_Error_St                                0x9   ,  0xfdff    
#define AI_Status_1__AI_Overflow_St                                   0xa   ,  0xfbff    
#define AI_Status_1__AI_Overrun_St                                    0xb   ,  0xf7ff    
#define AI_Status_1__AI_FIFO_Empty_St                                 0xc   ,  0xefff    
#define AI_Status_1__AI_FIFO_Half_Full_St                             0xd   ,  0xdfff    
#define AI_Status_1__AI_FIFO_Full_St                                  0xe   ,  0xbfff    
#define AI_Status_1__Interrupt_Group_A_Status                         0xf   ,  0x7fff    
#define Analog_Trigger_Etc__Analog_Trigger_Mode                       0x0   ,  0xfff8    
#define Analog_Trigger_Etc__Analog_Trigger_Enable                     0x3   ,  0xfff7    
#define Analog_Trigger_Etc__Analog_Trigger_Reset                      0x5   ,  0xffdf    
#define Analog_Trigger_Etc__Misc_Counter_TCs_Output_Enable            0x6   ,  0xffbf    
#define Analog_Trigger_Etc__GPFO_1_Output_Select                      0x7   ,  0xff7f    
#define Analog_Trigger_Etc__GPFO_0_Output_Select                      0xb   ,  0xc7ff    
#define Analog_Trigger_Etc__GPFO_0_Output_Enable                      0xe   ,  0xbfff    
#define Analog_Trigger_Etc__GPFO_1_Output_Enable                      0xf   ,  0x7fff    
#define AI_Trigger_Select__AI_START1_Select                           0x0   ,  0xffe0    
#define AI_Trigger_Select__AI_START1_Edge                             0x5   ,  0xffdf    
#define AI_Trigger_Select__AI_START1_Sync                             0x6   ,  0xffbf    
#define AI_Trigger_Select__AI_START2_Select                           0x7   ,  0xf07f    
#define AI_Trigger_Select__AI_START2_Edge                             0xc   ,  0xefff    
#define AI_Trigger_Select__AI_START2_Sync                             0xd   ,  0xdfff    
#define AI_Trigger_Select__AI_START2_Polarity                         0xe   ,  0xbfff    
#define AI_Trigger_Select__AI_START1_Polarity                         0xf   ,  0x7fff    
#define AO_Command_2__AO_START1_Pulse                                 0x0   ,  0xfffe    
#define AO_Command_2__AO_Mute_A                                       0x2   ,  0xfffb    
#define AO_Command_2__AO_Mute_B                                       0x3   ,  0xfff7    
#define AO_Command_2__AO_BC_Switch_Load_On_TC                         0x4   ,  0xffef    
#define AO_Command_2__AO_UC_Switch_Load_On_TC                         0x5   ,  0xffdf    
#define AO_Command_2__AO_UC_Switch_Load_On_BC_TC                      0x6   ,  0xffbf    
#define AO_Command_2__AO_UI_Switch_Load_On_TC                         0x7   ,  0xff7f    
#define AO_Command_2__AO_UI_Switch_Load_On_Stop                       0x8   ,  0xfeff    
#define AO_Command_2__AO_UI_Switch_Load_On_BC_TC                      0x9   ,  0xfdff    
#define AO_Command_2__AO_BC_Save_Trace                                0xa   ,  0xfbff    
#define AO_Command_2__AO_BC_Gate_Enable                               0xb   ,  0xf7ff    
#define AO_Command_2__AO_UC_Save_Trace                                0xc   ,  0xefff    
#define AO_Command_2__AO_Start_Stop_Gate_Enable                       0xd   ,  0xdfff    
#define AO_Command_2__AO_End_On_UC_TC                                 0xe   ,  0xbfff    
#define AO_Command_2__AO_End_On_BC_TC                                 0xf   ,  0x7fff    
#define AO_Command_1__AO_UPDATE_Pulse                                 0x0   ,  0xfffe    
#define AO_Command_1__AO_DAC0_Update_Mode                             0x2   ,  0xfffb    
#define AO_Command_1__AO_DAC1_Update_Mode                             0x4   ,  0xffef    
#define AO_Command_1__AO_BC_Load                                      0x5   ,  0xffdf    
#define AO_Command_1__AO_BC_Arm                                       0x6   ,  0xffbf    
#define AO_Command_1__AO_UC_Load                                      0x7   ,  0xff7f    
#define AO_Command_1__AO_UC_Arm                                       0x8   ,  0xfeff    
#define AO_Command_1__AO_UI_Load                                      0x9   ,  0xfdff    
#define AO_Command_1__AO_UI_Arm                                       0xa   ,  0xfbff    
#define AO_Command_1__AO_Disarm                                       0xd   ,  0xdfff    
#define AO_Command_1__AO_START_Pulse                                  0xe   ,  0xbfff    
#define AO_Command_1__AO_Analog_Trigger_Reset                         0xf   ,  0x7fff    
#define AO_Mode_1__AO_Trigger_Once                                    0x0   ,  0xfffe    
#define AO_Mode_1__AO_Continuous                                      0x1   ,  0xfffd    
#define AO_Mode_1__AO_UC_Switch_Load_Every_TC                         0x2   ,  0xfffb    
#define AO_Mode_1__AO_UI_Source_Polarity                              0x3   ,  0xfff7    
#define AO_Mode_1__AO_UPDATE_Source_Polarity                          0x4   ,  0xffef    
#define AO_Mode_1__AO_Multiple_Channels                               0x5   ,  0xffdf    
#define AO_Mode_1__AO_UI_Source_Select                                0x6   ,  0xf83f    
#define AO_Mode_1__AO_UPDATE_Source_Select                            0xb   ,  0x7ff     
#define AO_Mode_2__AO_BC_Write_Switch                                 0x0   ,  0xfffe    
#define AO_Mode_2__AO_BC_Reload_Mode                                  0x1   ,  0xfffd    
#define AO_Mode_2__AO_BC_Initial_Load_Source                          0x2   ,  0xfffb    
#define AO_Mode_2__AO_UI_Write_Switch                                 0x3   ,  0xfff7    
#define AO_Mode_2__AO_UI_Reload_Mode                                  0x4   ,  0xff8f    
#define AO_Mode_2__AO_UI_Initial_Load_Source                          0x7   ,  0xff7f    
#define AO_Mode_2__AO_UC_Write_Switch                                 0xa   ,  0xfbff    
#define AO_Mode_2__AO_UC_Initial_Load_Source                          0xb   ,  0xf7ff    
#define AO_Mode_2__AO_START1_Disable                                  0xc   ,  0xefff    
#define AO_Mode_2__AO_FIFO_Retransmit_Enable                          0xd   ,  0xdfff    
#define AO_Mode_2__AO_FIFO_Mode                                       0xe   ,  0x3fff    
#define AO_Output_Control__AO_UPDATE_Output_Select                    0x0   ,  0xfffc    
#define AO_Output_Control__AO_External_Gate_Polarity                  0x3   ,  0xfff7    
#define AO_Output_Control__AO_Number_Of_Channels                      0x6   ,  0xfc3f    
#define AO_Output_Control__AO_External_Gate_Select                    0xa   ,  0x83ff    
#define AO_Output_Control__AO_External_Gate_Enable                    0xf   ,  0x7fff    
#define AO_Mode_3__AO_Last_Gate_Disable                               0x0   ,  0xfffe    
#define AO_Mode_3__AO_Software_Gate                                   0x1   ,  0xfffd    
#define AO_Mode_3__AO_Not_An_UPDATE                                   0x2   ,  0xfffb    
#define AO_Mode_3__AO_Stop_On_BC_TC_Error                             0x3   ,  0xfff7    
#define AO_Mode_3__AO_Stop_On_BC_TC_Trigger_Error                     0x4   ,  0xffef    
#define AO_Mode_3__AO_Stop_On_Overrun_Error                           0x5   ,  0xffdf    
#define AO_Mode_3__AO_Trigger_Length                                  0xb   ,  0xf7ff    
#define AO_Mode_3__AO_UC_Switch_Load_Every_BC_TC                      0xc   ,  0xefff    
#define AO_Personal__AO_Interval_Buffer_Mode                          0x3   ,  0xfff7    
#define AO_Personal__AO_BC_Source_Select                              0x4   ,  0xffef    
#define AO_Personal__AO_UPDATE_Pulse_Width                            0x5   ,  0xffdf    
#define AO_Personal__AO_UPDATE_Pulse_Timebase                         0x6   ,  0xffbf    
#define AO_Personal__AO_UPDATE_Original_Pulse                         0x7   ,  0xff7f    
#define AO_Personal__AO_FIFO_Enable                                   0xa   ,  0xfbff    
#define AO_Personal__AO_TMRDACWR_Pulse_Width                          0xc   ,  0xefff    
#define AO_Personal__AO_Number_Of_DAC_Packages                        0xe   ,  0xbfff    
#define AO_Personal__AO_Multiple_DACS_Per_Package                     0xf   ,  0x7fff    
#define AO_START_Select__AO_START_Edge                                0x5   ,  0xffdf    
#define AO_START_Select__AO_START_Sync                                0x6   ,  0xffbf    
#define AO_START_Select__AO_AOFREQ_Enable                             0xc   ,  0xefff    
#define AO_START_Select__AO_START_Polarity                            0xd   ,  0xdfff    
#define AO_Status_2__AO_BC_Armed_St                                   0x0   ,  0xfffe    
#define AO_Status_2__AO_BC_Save_St                                    0x2   ,  0xfffb    
#define AO_Status_2__AO_BC_Q_St                                       0x3   ,  0xfff7    
#define AO_Status_2__AO_BC_TC_Trigger_Error_St                        0x4   ,  0xffef    
#define AO_Status_2__AO_UI_Armed_St                                   0x5   ,  0xffdf    
#define AO_Status_2__AO_UI_Next_Load_Source_St                        0x6   ,  0xffbf    
#define AO_Status_2__AO_UC_Save_St                                    0x7   ,  0xff7f    
#define AO_Status_2__AO_UI_Count_Enabled_St                           0x8   ,  0xfeff    
#define AO_Status_2__AO_UI_Q_St                                       0x9   ,  0xfdff    
#define AO_Status_2__AO_UC_Armed_St                                   0xe   ,  0xbfff    
#define AO_Status_1__Pass_Thru_1_Interrupt_St                         0x0   ,  0xfffe    
#define AO_Status_1__AO_FIFO_Request_St                               0x1   ,  0xfffd    
#define AO_Status_1__G1_Gate_Interrupt_St                             0x2   ,  0xfffb    
#define AO_Status_1__G1_TC_St                                         0x3   ,  0xfff7    
#define AO_Status_1__AO_UPDATE_St                                     0x5   ,  0xffdf    
#define AO_Status_1__AO_UC_TC_St                                      0x6   ,  0xffbf    
#define AO_Status_1__AO_BC_TC_St                                      0x7   ,  0xff7f    
#define AO_Status_1__AO_START1_St                                     0x8   ,  0xfeff    
#define AO_Status_1__AO_Overrun_St                                    0x9   ,  0xfdff    
#define AO_Status_1__AO_START_St                                      0xa   ,  0xfbff    
#define AO_Status_1__AO_BC_TC_Error_St                                0xb   ,  0xf7ff    
#define AO_Status_1__AO_FIFO_Empty_St                                 0xc   ,  0xefff    
#define AO_Status_1__AO_FIFO_Half_Full_St                             0xd   ,  0xdfff    
#define AO_Status_1__AO_FIFO_Full_St                                  0xe   ,  0xbfff    
#define AO_Status_1__Interrupt_Group_B_Status                         0xf   ,  0x7fff    
#define AO_Trigger_Select__AO_START1_Select                           0x0   ,  0xffe0    
#define AO_Trigger_Select__AO_START1_Edge                             0x5   ,  0xffdf    
#define AO_Trigger_Select__AO_START1_Sync                             0x6   ,  0xffbf    
#define AO_Trigger_Select__AO_START1_Polarity                         0xd   ,  0xdfff    
#define AO_Trigger_Select__AO_Delayed_START1                          0xe   ,  0xbfff    
#define Clock_and_FOUT__FOUT_Divider                                  0x0   ,  0xfff0    
#define Clock_and_FOUT__Clock_To_Board                                0x8   ,  0xfeff    
#define Clock_and_FOUT__Clock_To_Board_Divide_By_2                    0x9   ,  0xfdff    
#define Clock_and_FOUT__Slow_Internal_Timebase                        0xb   ,  0xf7ff    
#define Clock_and_FOUT__DIO_Serial_Out_Divide_By_2                    0xd   ,  0xdfff    
#define Clock_and_FOUT__FOUT_Timebase_Select                          0xe   ,  0xbfff    
#define Clock_and_FOUT__FOUT_Enable                                   0xf   ,  0x7fff    
#define Interrupt_A_Ack__G0_Gate_Error_Confirm                        0x5   ,  0xffdf    
#define Interrupt_A_Ack__G0_TC_Error_Confirm                          0x6   ,  0xffbf    
#define Interrupt_A_Ack__AI_SC_TC_Error_Confirm                       0x7   ,  0xff7f    
#define Interrupt_A_Ack__AI_SC_TC_Interrupt_Ack                       0x8   ,  0xfeff    
#define Interrupt_A_Ack__AI_START1_Interrupt_Ack                      0x9   ,  0xfdff    
#define Interrupt_A_Ack__AI_START2_Interrupt_Ack                      0xa   ,  0xfbff    
#define Interrupt_A_Ack__AI_START_Interrupt_Ack                       0xb   ,  0xf7ff    
#define Interrupt_A_Ack__AI_STOP_Interrupt_Ack                        0xc   ,  0xefff    
#define Interrupt_A_Ack__AI_Error_Interrupt_Ack                       0xd   ,  0xdfff    
#define Interrupt_A_Ack__G0_TC_Interrupt_Ack                          0xe   ,  0xbfff    
#define Interrupt_A_Ack__G0_Gate_Interrupt_Ack                        0xf   ,  0x7fff    
#define Interrupt_A_Enable__AI_SC_TC_Interrupt_Enable                 0x0   ,  0xfffe    
#define Interrupt_A_Enable__AI_START1_Interrupt_Enable                0x1   ,  0xfffd    
#define Interrupt_A_Enable__AI_START2_Interrupt_Enable                0x2   ,  0xfffb    
#define Interrupt_A_Enable__AI_START_Interrupt_Enable                 0x3   ,  0xfff7    
#define Interrupt_A_Enable__AI_STOP_Interrupt_Enable                  0x4   ,  0xffef    
#define Interrupt_A_Enable__AI_Error_Interrupt_Enable                 0x5   ,  0xffdf    
#define Interrupt_A_Enable__G0_TC_Interrupt_Enable                    0x6   ,  0xffbf    
#define Interrupt_A_Enable__AI_FIFO_Interrupt_Enable                  0x7   ,  0xff7f    
#define Interrupt_A_Enable__G0_Gate_Interrupt_Enable                  0x8   ,  0xfeff    
#define Interrupt_B_Ack__G1_Gate_Error_Confirm                        0x1   ,  0xfffd    
#define Interrupt_B_Ack__G1_TC_Error_Confirm                          0x2   ,  0xfffb    
#define Interrupt_B_Ack__AO_BC_TC_Trigger_Error_Confirm               0x3   ,  0xfff7    
#define Interrupt_B_Ack__AO_BC_TC_Error_Confirm                       0x4   ,  0xffef    
#define Interrupt_B_Ack__AO_UC_TC_Interrupt_Ack                       0x7   ,  0xff7f    
#define Interrupt_B_Ack__AO_BC_TC_Interrupt_Ack                       0x8   ,  0xfeff    
#define Interrupt_B_Ack__AO_START1_Interrupt_Ack                      0x9   ,  0xfdff    
#define Interrupt_B_Ack__AO_UPDATE_Interrupt_Ack                      0xa   ,  0xfbff    
#define Interrupt_B_Ack__AO_START_Interrupt_Ack                       0xb   ,  0xf7ff    
#define Interrupt_B_Ack__AO_STOP_Interrupt_Ack                        0xc   ,  0xefff    
#define Interrupt_B_Ack__AO_Error_Interrupt_Ack                       0xd   ,  0xdfff    
#define Interrupt_B_Ack__G1_TC_Interrupt_Ack                          0xe   ,  0xbfff    
#define Interrupt_B_Ack__G1_Gate_Interrupt_Ack                        0xf   ,  0x7fff    
#define Interrupt_Control__Interrupt_Group_A_Enable                   0xb   ,  0xf7ff    
#define Interrupt_Control__Interrupt_Group_B_Enable                   0xf   ,  0x7fff    
#define Interrupt_B_Enable__AO_BC_TC_Interrupt_Enable                 0x0   ,  0xfffe    
#define Interrupt_B_Enable__AO_START1_Interrupt_Enable                0x1   ,  0xfffd    
#define Interrupt_B_Enable__AO_UPDATE_Interrupt_Enable                0x2   ,  0xfffb    
#define Interrupt_B_Enable__AO_START_Interrupt_Enable                 0x3   ,  0xfff7    
#define Interrupt_B_Enable__AO_STOP_Interrupt_Enable                  0x4   ,  0xffef    
#define Interrupt_B_Enable__AO_Error_Interrupt_Enable                 0x5   ,  0xffdf    
#define Interrupt_B_Enable__AO_UC_TC_Interrupt_Enable                 0x6   ,  0xffbf    
#define Interrupt_B_Enable__AO_FIFO_Interrupt_Enable                  0x8   ,  0xfeff    
#define Interrupt_B_Enable__G1_TC_Interrupt_Enable                    0x9   ,  0xfdff    
#define Interrupt_B_Enable__G1_Gate_Interrupt_Enable                  0xa   ,  0xfbff    
#define Interrupt_B_Enable__Pass_Thru_1_Interrupt_Enable              0xb   ,  0xf7ff    
#define IO_Bidirection_Pin__PFI0_Pin_Dir                              0x0   ,  0xfffe    
#define IO_Bidirection_Pin__PFI1_Pin_Dir                              0x1   ,  0xfffd    
#define IO_Bidirection_Pin__PFI2_Pin_Dir                              0x2   ,  0xfffb    
#define IO_Bidirection_Pin__PFI3_Pin_Dir                              0x3   ,  0xfff7    
#define IO_Bidirection_Pin__PFI4_Pin_Dir                              0x4   ,  0xffef    
#define IO_Bidirection_Pin__PFI5_Pin_Dir                              0x5   ,  0xffdf    
#define IO_Bidirection_Pin__PFI6_Pin_Dir                              0x6   ,  0xffbf    
#define IO_Bidirection_Pin__PFI7_Pin_Dir                              0x7   ,  0xff7f    
#define IO_Bidirection_Pin__PFI8_Pin_Dir                              0x8   ,  0xfeff    
#define IO_Bidirection_Pin__PFI9_Pin_Dir                              0x9   ,  0xfdff    
#define IO_Bidirection_Pin__PFI10_Pin_Dir                             0xa   ,  0xfbff    
#define IO_Bidirection_Pin__PFI11_Pin_Dir                             0xb   ,  0xf7ff    
#define IO_Bidirection_Pin__PFI12_Pin_Dir                             0xc   ,  0xefff    
#define IO_Bidirection_Pin__PFI13_Pin_Dir                             0xd   ,  0xdfff    
#define IO_Bidirection_Pin__PFI14_Pin_Dir                             0xe   ,  0xbfff    
#define IO_Bidirection_Pin__PFI15_Pin_Dir                             0xf   ,  0x7fff    
#define Joint_Reset__AI_Reset                                         0x0   ,  0xfffe    
#define Joint_Reset__AO_Reset                                         0x1   ,  0xfffd    
#define Joint_Reset__G0_Reset                                         0x2   ,  0xfffb    
#define Joint_Reset__G1_Reset                                         0x3   ,  0xfff7    
#define Joint_Reset__AI_Configuration_Start                           0x4   ,  0xffef    
#define Joint_Reset__AO_Configuration_Start                           0x5   ,  0xffdf    
#define Joint_Reset__AI_Configuration_End                             0x8   ,  0xfeff    
#define Joint_Reset__AO_Configuration_End                             0x9   ,  0xfdff    
#define Joint_Reset__Software_Reset                                   0xb   ,  0xf7ff    
#define Joint_Status_2__G0_Output_St                                  0x0   ,  0xfffe    
#define Joint_Status_2__G1_Output_St                                  0x1   ,  0xfffd    
#define Joint_Status_2__AO_STOP_St                                    0x2   ,  0xfffb    
#define Joint_Status_2__AI_EOC_St                                     0x4   ,  0xffef    
#define Joint_Status_2__AO_TMRDACWRs_In_Progress_St                   0x5   ,  0xffdf    
#define Joint_Status_2__AI_Config_Memory_Empty_St                     0x6   ,  0xffbf    
#define Joint_Status_2__AI_Scan_In_Progress_St                        0x7   ,  0xff7f    
#define Joint_Status_2__Generic_Status                                0x8   ,  0xf0ff    
#define Joint_Status_2__G0_HW_Save_St                                 0xc   ,  0xefff    
#define Joint_Status_2__G1_HW_Save_St                                 0xd   ,  0xdfff    
#define Joint_Status_2__G0_Permanent_Stale_Data_St                    0xe   ,  0xbfff    
#define Joint_Status_2__G1_Permanent_Stale_Data_St                    0xf   ,  0x7fff    
#define Joint_Status_1__G0_Bank_St                                    0x0   ,  0xfffe    
#define Joint_Status_1__G1_Bank_St                                    0x1   ,  0xfffd    
#define Joint_Status_1__G0_Gate_St                                    0x2   ,  0xfffb    
#define Joint_Status_1__G1_Gate_St                                    0x3   ,  0xfff7    
#define Joint_Status_1__AI_SC_Gate_St                                 0x4   ,  0xffef    
#define Joint_Status_1__AI_Start_Stop_Gate_St                         0x5   ,  0xffdf    
#define Joint_Status_1__AO_BC_Gate_St                                 0x6   ,  0xffbf    
#define Joint_Status_1__AO_Start_Stop_Gate_St                         0x7   ,  0xff7f    
#define Joint_Status_1__AI_SI2_Q_St                                   0x8   ,  0xfcff    
#define Joint_Status_1__AI_External_Gate_St                           0xa   ,  0xfbff    
#define Joint_Status_1__AO_External_Gate_St                           0xb   ,  0xf7ff    
#define Joint_Status_1__DIO_Serial_IO_In_Progress_St                  0xc   ,  0xefff    
#define Joint_Status_1__AO_UC_Q_St                                    0xe   ,  0xbfff    
#define Joint_Status_1__AI_Last_Shiftin_St                            0xf   ,  0x7fff    
#define RTSI_Shared_MUX__RTSI_Shared_MUX_0_Output_Select              0x0   ,  0xfff0    
#define RTSI_Shared_MUX__RTSI_Shared_MUX_1_Output_Select              0x4   ,  0xff0f    
#define RTSI_Shared_MUX__RTSI_Shared_MUX_2_Output_Select              0x8   ,  0xf0ff    
#define RTSI_Shared_MUX__RTSI_Shared_MUX_3_Output_Select              0xc   ,  0xfff     
#define RTSI_Trig_A_Output__RTSI0_Output_Select                       0x0   ,  0xfff0    
#define RTSI_Trig_A_Output__RTSI1_Output_Select                       0x4   ,  0xff0f    
#define RTSI_Trig_A_Output__RTSI2_Output_Select                       0x8   ,  0xf0ff    
#define RTSI_Trig_A_Output__RTSI3_Output_Select                       0xc   ,  0xfff     
#define RTSI_Trig_Direction__Drive_RTSI_OSC                           0x0   ,  0xfffe    
#define RTSI_Trig_Direction__Use_RTSI_OSC                             0x1   ,  0xfffd    
#define RTSI_Trig_Direction__RTSI_Sub_Selection_1                     0x2   ,  0xfffb    
#define RTSI_Trig_Direction__RTSI0_Pin_Dir                            0x8   ,  0xfeff    
#define RTSI_Trig_Direction__RTSI1_Pin_Dir                            0x9   ,  0xfdff    
#define RTSI_Trig_Direction__RTSI2_Pin_Dir                            0xa   ,  0xfbff    
#define RTSI_Trig_Direction__RTSI3_Pin_Dir                            0xb   ,  0xf7ff    
#define RTSI_Trig_Direction__RTSI4_Pin_Dir                            0xc   ,  0xefff    
#define RTSI_Trig_Direction__RTSI5_Pin_Dir                            0xd   ,  0xdfff    
#define RTSI_Trig_Direction__RTSI6_Pin_Dir                            0xe   ,  0xbfff    
#define RTSI_Trig_Direction__RTSI7_Pin_Dir                            0xf   ,  0x7fff    
#define RTSI_Trig_B_Output__RTSI4_Output_Select                       0x0   ,  0xfff0    
#define RTSI_Trig_B_Output__RTSI5_Output_Select                       0x4   ,  0xff0f    
#define RTSI_Trig_B_Output__RTSI6_Output_Select                       0x8   ,  0xf0ff    
#define RTSI_Trig_B_Output__RTSI7_Output_Select                       0xc   ,  0xfff     
#define G0_DMA_Config__G0_DMA_Enable                                  0x0   ,  0xfffe    
#define G0_DMA_Config__G0_DMA_Write                                   0x1   ,  0xfffd    
#define G0_DMA_Config__G0_DMA_Int_Enable                              0x2   ,  0xfffb    
#define G0_DMA_Config__G0_DMA_Reset                                   0x3   ,  0xfff7    
#define G0_DMA_Config__G0_DMA_BankSW_Error                            0x4   ,  0xffef    
#define G1_DMA_Config__G1_DMA_Enable                                  0x0   ,  0xfffe    
#define G1_DMA_Config__G1_DMA_Write                                   0x1   ,  0xfffd    
#define G1_DMA_Config__G1_DMA_Int_Enable                              0x2   ,  0xfffb    
#define G1_DMA_Config__G1_DMA_Reset                                   0x3   ,  0xfff7    
#define G1_DMA_Config__G1_DMA_BankSW_Error                            0x4   ,  0xffef    
#define G0_DMA_Status__G0_Pstat                                       0x0   ,  0xff00    
#define G0_DMA_Status__G0_DMA_Readbank                                0xd   ,  0xdfff    
#define G0_DMA_Status__G0_DRQ_Error_St                                0xe   ,  0xbfff    
#define G0_DMA_Status__G0_DRQ_St                                      0xf   ,  0x7fff    
#define G1_DMA_Status__G1_Pstat                                       0x0   ,  0xff00    
#define G1_DMA_Status__G1_DMA_Readbank                                0xd   ,  0xdfff    
#define G1_DMA_Status__G1_DRQ_Error_St                                0xe   ,  0xbfff    
#define G1_DMA_Status__G1_DRQ_St                                      0xf   ,  0x7fff    
#define CDIO_DMA_Select__CDI_DMA_Select                               0x0   ,  0xf0      
#define CDIO_DMA_Select__CDO_DMA_Select                               0x4   ,  0xf       
#define SCXI_Control__SCXI_SW_SPIClk                                  0x0   ,  0xfe      
#define SCXI_Control__SCXI_Back_Plane_MISO_Enable                     0x1   ,  0xfd      
#define SCXI_Control__SCXI_Front_Panel_MISO_Enable                    0x2   ,  0xfb      
#define SCXI_Control__SCXI_Intr                                       0x3   ,  0xf7      
#define SCXI_Control__SCXI_D_A                                        0x4   ,  0xef      
#define SCXI_Control__SCXI_HW_Serial_Timebase                         0x5   ,  0xdf      
#define SCXI_Control__SCXI_HW_Serial_Start                            0x6   ,  0xbf      
#define SCXI_Control__SCXI_HW_Serial_Enable                           0x7   ,  0x7f      
#define AI_Mode_1__AI_Trigger_Once                                    0x0   ,  0xfffe    
#define AI_Mode_1__AI_Continuous                                      0x1   ,  0xfffd    
#define AI_Mode_1__AI_Start_Stop                                      0x3   ,  0xfff7    
#define AI_Mode_1__AI_SI_Source_Polarity                              0x4   ,  0xffef    
#define AI_Mode_1__AI_CONVERT_Source_Polarity                         0x5   ,  0xffdf    
#define AI_Mode_1__AI_SI_Source_Select                                0x6   ,  0xf83f    
#define AI_Mode_1__AI_CONVERT_Source_Select                           0xb   ,  0x7ff     
#define SCXI_Status__SCXI_Shift_In_Prog                               0x0   ,  0xfe      
#define SCXI_Output_Enable__SCXI_Dedicated_Output_Enable              0x0   ,  0xfe      
#define SCXI_Output_Enable__SCXI_Trig1_Output_Enable                  0x1   ,  0xfd      
#define SCXI_Output_Enable__SCXI_Trig0_Output_Enable                  0x2   ,  0xfb      
#define SCXI_Output_Enable__SCXI_Trig1_Output_Select                  0x3   ,  0x7       
#define SCXI_DIO_Enable__SCXI_DIO_MOSI_Enable                         0x0   ,  0xfe      
#define SCXI_DIO_Enable__SCXI_DIO_D_A_Enable                          0x1   ,  0xfd      
#define SCXI_DIO_Enable__SCXI_DIO_Intr_Enable                         0x2   ,  0xfb      
#define AO_Serial_Interrupt_Enable__AO_MUDS_0_Interrupt_Enable        0x0   ,  0xfe      
#define AO_Serial_Interrupt_Enable__AO_MUDS_1_Interrupt_Enable        0x1   ,  0xfd      
#define AO_Serial_Interrupt_Enable__AO_MUDS_2_Interrupt_Enable        0x2   ,  0xfb      
#define AO_Serial_Interrupt_Enable__AO_MUDS_3_Interrupt_Enable        0x3   ,  0xf7      
#define AO_Serial_Interrupt_Ack__AO_MUDS_0_Interrupt_Ack              0x0   ,  0xfe      
#define AO_Serial_Interrupt_Ack__AO_MUDS_1_Interrupt_Ack              0x1   ,  0xfd      
#define AO_Serial_Interrupt_Ack__AO_MUDS_2_Interrupt_Ack              0x2   ,  0xfb      
#define AO_Serial_Interrupt_Ack__AO_MUDS_3_Interrupt_Ack              0x3   ,  0xf7      
#define AO_Serial_Interrupt_Status__AO_MUDS_0_Interrupt_St            0x0   ,  0xfe      
#define AO_Serial_Interrupt_Status__AO_MUDS_1_Interrupt_St            0x1   ,  0xfd      
#define AO_Serial_Interrupt_Status__AO_MUDS_2_Interrupt_St            0x2   ,  0xfb      
#define AO_Serial_Interrupt_Status__AO_MUDS_3_Interrupt_St            0x3   ,  0xf7      
#define Interrupt_C_Enable__Interrupt_Group_C_Enable                  0x0   ,  0xfe      
#define Interrupt_C_Status__Interrupt_Group_C_Status                  0x0   ,  0xfe      
#define Analog_Trigger_Control__Analog_Trigger_Select                 0x0   ,  0xfc      
#define AI_AO_Select__AI_DMA_Select                                   0x0   ,  0xf0      
#define AI_AO_Select__AO_DMA_Select                                   0x4   ,  0xf       
#define AI_Config_FIFO_Data__AI_Config_Channel                        0x0   ,  0xfff0    
#define AI_Config_FIFO_Data__AI_Config_Bank                           0x4   ,  0xffcf    
#define AI_Config_FIFO_Data__AI_Config_Channel_Type                   0x6   ,  0xfe3f    
#define AI_Config_FIFO_Data__AI_Config_Gain                           0x9   ,  0xf1ff    
#define AI_Config_FIFO_Data__AI_Config_Polarity                       0xc   ,  0xefff    
#define AI_Config_FIFO_Data__AI_Config_Dither                         0xd   ,  0xdfff    
#define AI_Config_FIFO_Data__AI_Config_Last_Channel                   0xe   ,  0xbfff    
#define G0_G1_Select__G0_DMA_Select                                   0x0   ,  0xf0      
#define G0_G1_Select__G1_DMA_Select                                   0x4   ,  0xf       
#define Misc_Command__IntExtTrig                                      0x7   ,  0x7f      
#define AO_Calibration__AO_RefGround                                  0x0   ,  0xfe      
#define PFI_Output_Select_1__PFI0_Output_Select                       0x0   ,  0xffe0    
#define PFI_Output_Select_1__PFI1_Output_Select                       0x5   ,  0xfc1f    
#define PFI_Output_Select_1__PFI2_Output_Select                       0xa   ,  0x83ff    
#define PFI_Output_Select_2__PFI3_Output_Select                       0x0   ,  0xffe0    
#define PFI_Output_Select_2__PFI4_Output_Select                       0x5   ,  0xfc1f    
#define PFI_Output_Select_2__PFI5_Output_Select                       0xa   ,  0x83ff    
#define PFI_Output_Select_3__PFI6_Output_Select                       0x0   ,  0xffe0    
#define PFI_Output_Select_3__PFI7_Output_Select                       0x5   ,  0xfc1f    
#define PFI_Output_Select_3__PFI8_Output_Select                       0xa   ,  0x83ff    
#define PFI_Output_Select_4__PFI9_Output_Select                       0x0   ,  0xffe0    
#define PFI_Output_Select_4__PFI10_Output_Select                      0x5   ,  0xfc1f    
#define PFI_Output_Select_4__PFI11_Output_Select                      0xa   ,  0x83ff    
#define PFI_Output_Select_5__PFI12_Output_Select                      0x0   ,  0xffe0    
#define PFI_Output_Select_5__PFI13_Output_Select                      0x5   ,  0xfc1f    
#define PFI_Output_Select_5__PFI14_Output_Select                      0xa   ,  0x83ff    
#define PFI_Output_Select_6__PFI15_Output_Select                      0x0   ,  0xffe0    
#define PFI_DO__LowerPort                                             0x0   ,  0xff00    
#define PFI_DO__UpperPort                                             0x8   ,  0xff      
#define PFI_Filter__PFI0_Filter_Select                                0x0   ,  0xfffffffc
#define PFI_Filter__PFI1_Filter_Select                                0x2   ,  0xfffffff3
#define PFI_Filter__PFI2_Filter_Select                                0x4   ,  0xffffffcf
#define PFI_Filter__PFI3_Filter_Select                                0x6   ,  0xffffff3f
#define PFI_Filter__PFI4_Filter_Select                                0x8   ,  0xfffffcff
#define PFI_Filter__PFI5_Filter_Select                                0xa   ,  0xfffff3ff
#define PFI_Filter__PFI6_Filter_Select                                0xc   ,  0xffffcfff
#define PFI_Filter__PFI7_Filter_Select                                0xe   ,  0xffff3fff
#define PFI_Filter__PFI8_Filter_Select                                0x10  ,  0xfffcffff
#define PFI_Filter__PFI9_Filter_Select                                0x12  ,  0xfff3ffff
#define PFI_Filter__PFI10_Filter_Select                               0x14  ,  0xffcfffff
#define PFI_Filter__PFI11_Filter_Select                               0x16  ,  0xff3fffff
#define PFI_Filter__PFI12_Filter_Select                               0x18  ,  0xfcffffff
#define PFI_Filter__PFI13_Filter_Select                               0x1a  ,  0xf3ffffff
#define PFI_Filter__PFI14_Filter_Select                               0x1c  ,  0xcfffffff
#define PFI_Filter__PFI15_Filter_Select                               0x1e  ,  0x3fffffff
#define RTSI_Filter__RTSI0_Filter_Select                              0x0   ,  0xfffffffc
#define RTSI_Filter__RTSI1_Filter_Select                              0x2   ,  0xfffffff3
#define RTSI_Filter__RTSI2_Filter_Select                              0x4   ,  0xffffffcf
#define RTSI_Filter__RTSI3_Filter_Select                              0x6   ,  0xffffff3f
#define RTSI_Filter__RTSI4_Filter_Select                              0x8   ,  0xfffffcff
#define RTSI_Filter__RTSI5_Filter_Select                              0xa   ,  0xfffff3ff
#define RTSI_Filter__RTSI6_Filter_Select                              0xc   ,  0xffffcfff
#define RTSI_Filter__RTSI7_Filter_Select                              0xe   ,  0xffff3fff
#define Clock_And_Fout2__PLL_In_Source_Select                         0x0   ,  0xffe0    
#define Clock_And_Fout2__TB1_Select                                   0x5   ,  0xffdf    
#define Clock_And_Fout2__TB3_Select                                   0x6   ,  0xffbf    
#define Clock_And_Fout2__RTSI_Clock_Freq                              0x7   ,  0xff7f    
#define PLL_Control__PLL_Multiplier                                   0x0   ,  0xff00    
#define PLL_Control__PLL_Divisor                                      0x8   ,  0xf0ff    
#define PLL_Control__PLL_Enable                                       0xc   ,  0xefff    
#define PLL_Control__PLL_VCO_Mode                                     0xd   ,  0x9fff    
#define PLL_Status__PLL_Locked                                        0x0   ,  0xfffe    
#define AI_Config_FIFO_Bypass__AI_Bypass_Channel                      0x0   ,  0xfffffff8
#define AI_Config_FIFO_Bypass__AI_Bypass_Bank                         0x3   ,  0xffffff87
#define AI_Config_FIFO_Bypass__AI_Bypass_Cal_Sel_Pos                  0x7   ,  0xfffffc7f
#define AI_Config_FIFO_Bypass__AI_Bypass_Cal_Sel_Neg                  0xa   ,  0xffffe3ff
#define AI_Config_FIFO_Bypass__AI_Bypass_Mode_Mux                     0xd   ,  0xffff9fff
#define AI_Config_FIFO_Bypass__AO_Bypass_AO_Cal_Sel                   0xf   ,  0xfffc7fff
#define AI_Config_FIFO_Bypass__AI_Bypass_Gain                         0x12  ,  0xffe3ffff
#define AI_Config_FIFO_Bypass__AI_Bypass_Dither                       0x15  ,  0xffdfffff
#define AI_Config_FIFO_Bypass__AI_Bypass_Polarity                     0x16  ,  0xffbfffff
#define AI_Config_FIFO_Bypass__AI_Bypass_Config_FIFO                  0x1f  ,  0x7fffffff
#define CDIO_Status__CDO_FIFO_Empty_St                                0x0   ,  0xfffffffe
#define CDIO_Status__CDO_FIFO_Full_St                                 0x1   ,  0xfffffffd
#define CDIO_Status__CDO_FIFO_Request_St                              0x2   ,  0xfffffffb
#define CDIO_Status__CDO_Overrun_St                                   0x3   ,  0xfffffff7
#define CDIO_Status__CDO_Underflow_St                                 0x4   ,  0xffffffef
#define CDIO_Status__CDI_FIFO_Empty_St                                0x10  ,  0xfffeffff
#define CDIO_Status__CDI_FIFO_Full_St                                 0x11  ,  0xfffdffff
#define CDIO_Status__CDI_FIFO_Request_St                              0x12  ,  0xfffbffff
#define CDIO_Status__CDI_Overrun_St                                   0x13  ,  0xfff7ffff
#define CDIO_Status__CDI_Overflow_St                                  0x14  ,  0xffefffff
#define CDIO_Command__CDO_Disarm                                      0x0   ,  0xfffffffe
#define CDIO_Command__CDO_Arm                                         0x1   ,  0xfffffffd
#define CDIO_Command__CDI_Disarm                                      0x2   ,  0xfffffffb
#define CDIO_Command__CDI_Arm                                         0x3   ,  0xfffffff7
#define CDIO_Command__CDO_Reset                                       0x4   ,  0xffffffef
#define CDIO_Command__CDI_Reset                                       0x5   ,  0xffffffdf
#define CDIO_Command__CDO_Error_Interrupt_Enable_Set                  0x6   ,  0xffffffbf
#define CDIO_Command__CDO_Error_Interrupt_Enable_Clear                0x7   ,  0xffffff7f
#define CDIO_Command__CDI_Error_Interrupt_Enable_Set                  0x8   ,  0xfffffeff
#define CDIO_Command__CDI_Error_Interrupt_Enable_Clear                0x9   ,  0xfffffdff
#define CDIO_Command__CDO_FIFO_Request_Interrupt_Enable_Set           0xa   ,  0xfffffbff
#define CDIO_Command__CDO_FIFO_Request_Interrupt_Enable_Clear         0xb   ,  0xfffff7ff
#define CDIO_Command__CDI_FIFO_Request_Interrupt_Enable_Set           0xc   ,  0xffffefff
#define CDIO_Command__CDI_FIFO_Request_Interrupt_Enable_Clear         0xd   ,  0xffffdfff
#define CDIO_Command__CDO_Error_Interrupt_Confirm                     0xe   ,  0xffffbfff
#define CDIO_Command__CDI_Error_Interrupt_Confirm                     0xf   ,  0xffff7fff
#define CDIO_Command__CDO_Empty_FIFO_Interrupt_Enable_Set             0x10  ,  0xfffeffff
#define CDIO_Command__CDO_Empty_FIFO_Interrupt_Enable_Clear           0x11  ,  0xfffdffff
#define CDIO_Command__CDO_SW_Update                                   0x13  ,  0xfff7ffff
#define CDIO_Command__CDI_SW_Sample                                   0x14  ,  0xffefffff
#define CDI_Mode__CDI_Sample_Source_Select                            0x0   ,  0xffffffc0
#define CDI_Mode__CDI_Halt_On_Error                                   0x9   ,  0xfffffdff
#define CDI_Mode__CDI_Polarity                                        0xa   ,  0xfffffbff
#define CDI_Mode__CDI_FIFO_Mode                                       0xb   ,  0xfffff7ff
#define CDI_Mode__CDI_Data_Lane                                       0xc   ,  0xffffcfff
#define CDO_Mode__CDO_Update_Source_Select                            0x0   ,  0xffffffc0
#define CDO_Mode__CDO_Retransmit                                      0x8   ,  0xfffffeff
#define CDO_Mode__CDO_Halt_On_Error                                   0x9   ,  0xfffffdff
#define CDO_Mode__CDO_Polarity                                        0xa   ,  0xfffffbff
#define CDO_Mode__CDO_FIFO_Mode                                       0xb   ,  0xfffff7ff
#define CDO_Mode__CDO_Data_Lane                                       0xc   ,  0xffffcfff
#define SCXI_Legacy_Compatibility__SCXI_Force_AI_EXTMUX_CLK_Width     0x0   ,  0xfe      
#define DIO_Reserved_0__Value                                         0x0   ,  0x0       
#define DIO_Reserved_1__Value                                         0x0   ,  0x0       
#define DIO_Reserved_2__Value                                         0x0   ,  0x0       
#define DIO_Reserved_3__Value                                         0x0   ,  0x0       
#define DIO_Reserved_4__Value                                         0x0   ,  0x0       
#define DIO_Reserved_5__Value                                         0x0   ,  0x0       
#define DIO_Reserved_6__Value                                         0x0   ,  0x0       
#define DIO_Reserved_7__Value                                         0x0   ,  0x0       
#define LB_Reserved_0__Value0                                         0x0   ,  0xfff8    
#define LB_Reserved_0__Value1                                         0x8   ,  0xe0ff    
#define LB_Reserved_1__Value                                          0x0   ,  0x0       
#define AO_Config_Bank__AO_DAC_Offset_Select                          0x0   ,  0xf8      
#define AO_Config_Bank__AO_DAC_Reference_Select                       0x3   ,  0xc7      
#define AO_Config_Bank__AO_Update_Mode                                0x6   ,  0xbf      
#define AO_Config_Bank__AO_DAC_Polarity                               0x7   ,  0x7f      
#define Cal_PWM__Low_Time                                             0x0   ,  0xffff0000
#define Cal_PWM__High_Time                                            0x10  ,  0xffff    
