/*
 *
 * The following tables are derived from National Instruments examples
 * under their Copyright:
 *
 * Copyright (c) 2006, National Instruments Corporation
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of National Instruments Corporation nor the names of its
 *    contributors may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 *  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 *  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 *  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 *  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 *  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 *  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 *
 */

         
#define _kAI_CONVERT_Pulse 1
#define _kAI_LOCALMUX_CLK_Pulse 3
#define _kAI_EXTMUX_CLK_Pulse 4
#define _kAI_SCAN_IN_PROG_Pulse 5
#define _kAI_SC_Load 6
#define _kAI_SC_Arm 7
#define _kAI_DIV_Load 8
#define _kAI_DIV_Arm 9
#define _kAI_SI_Load 10
#define _kAI_SI_Arm 11
#define _kAI_SI2_Load 12
#define _kAI_SI2_Arm 13
#define _kAI_Disarm 14
#define _kAI_Analog_Trigger_Reset 15
         
#define _kAI_START1_Pulse 1
#define _kAI_START2_Pulse 2
#define _kAI_START_Pulse 3
#define _kAI_STOP_Pulse 4
#define _kAI_SC_Switch_Load_On_TC 5
#define _kAI_SI_Switch_Load_On_TC 8
#define _kAI_SI_Switch_Load_On_STOP 9
#define _kAI_SI_Switch_Load_On_SC_TC 10
#define _kAI_SC_Save_Trace 11
#define _kAI_START1_Disable 12
#define _kAI_End_On_End_Of_Scan 15
#define _kAI_End_On_SC_TC 16
         
#define _kAI_SC_Write_Switch 1
#define _kAI_SC_Reload_Mode 2
#define _kAI_SC_Initial_Load_Source 3
#define _kAI_SI_Write_Switch 4
#define _kAI_SI_Reload_Mode 5
#define _kAI_SI_Initial_Load_Source 6
#define _kAI_SI2_Reload_Mode 7
#define _kAI_SI2_Initial_Load_Source 8
#define _kAI_External_MUX_Present 11
#define _kAI_Pre_Trigger 12
#define _kAI_Start_Stop_Gate_Enable 13
#define _kAI_SC_Gate_Enable 14
#define _kAI_SC_Reload_ModeNo_Change 0
#define _kAI_SC_Reload_ModeSwitch 1
#define _kAI_SC_Initial_Load_SourceLoad_A 0
#define _kAI_SC_Initial_Load_SourceLoad_B 1
#define _kAI_SI_Reload_ModeNo_Change 0
#define _kAI_SI_Reload_ModeAlternate_First_Period_Every_STOP 4
#define _kAI_SI_Reload_ModeSwitch_Every_STOP 5
#define _kAI_SI_Reload_ModeAlternate_First_Period_Every_SCTC 6
#define _kAI_SI_Reload_ModeSwitch_Every_SCTC 7
#define _kAI_SI_Initial_Load_SourceLoad_A 0
#define _kAI_SI_Initial_Load_SourceLoad_B 1
#define _kAI_SI2_Reload_ModeNo_Change 0
#define _kAI_SI2_Reload_ModeAlternate_First_Period_Every_STOP 1
#define _kAI_SI2_Initial_Load_SourceLoad_A 0
#define _kAI_SI2_Initial_Load_SourceLoad_B 1
#define _kAI_External_MUX_PresentEvery_Convert 0
#define _kAI_External_MUX_PresentDIV_TC_Converts 1
         
#define _kAI_External_Gate_Select 1
#define _kAI_External_Gate_Polarity 2
#define _kAI_FIFO_Mode 3
#define _kAI_External_Gate_Mode 4
#define _kAI_Delayed_START1 5
#define _kAI_Delayed_START2 6
#define _kAI_SI2_Source_Select 7
#define _kAI_Software_Gate 9
#define _kAI_Delay_START 10
#define _kAI_Trigger_Length 11
#define _kAI_External_Gate_SelectDisabled 0
#define _kAI_External_Gate_SelectPFI0 1
#define _kAI_External_Gate_SelectPFI1 2
#define _kAI_External_Gate_SelectPFI2 3
#define _kAI_External_Gate_SelectPFI3 4
#define _kAI_External_Gate_SelectPFI4 5
#define _kAI_External_Gate_SelectPFI5 6
#define _kAI_External_Gate_SelectPFI6 7
#define _kAI_External_Gate_SelectPFI7 8
#define _kAI_External_Gate_SelectPFI8 9
#define _kAI_External_Gate_SelectPFI9 10
#define _kAI_External_Gate_SelectRTSI0 11
#define _kAI_External_Gate_SelectRTSI1 12
#define _kAI_External_Gate_SelectRTSI2 13
#define _kAI_External_Gate_SelectRTSI3 14
#define _kAI_External_Gate_SelectRTSI4 15
#define _kAI_External_Gate_SelectRTSI5 16
#define _kAI_External_Gate_SelectRTSI6 17
#define _kAI_External_Gate_SelectStar_Trigger 20
#define _kAI_External_Gate_SelectPFI10 21
#define _kAI_External_Gate_SelectPFI11 22
#define _kAI_External_Gate_SelectPFI12 23
#define _kAI_External_Gate_SelectPFI13 24
#define _kAI_External_Gate_SelectPFI14 25
#define _kAI_External_Gate_SelectPFI15 26
#define _kAI_External_Gate_SelectRTSI7 27
#define _kAI_External_Gate_SelectAnalog_Trigger 30
#define _kAI_External_Gate_SelectLow 31
#define _kAI_External_Gate_PolarityActive_High 0
#define _kAI_External_Gate_PolarityActive_Low 1
#define _kAI_FIFO_ModeNot_Empty 0
#define _kAI_FIFO_ModeHalf_Full 1
#define _kAI_FIFO_ModeFull 2
#define _kAI_FIFO_ModeHalf_Full_Until_Empty 3
#define _kAI_External_Gate_ModeFree_Run 0
#define _kAI_External_Gate_ModeHalt_Gating 1
#define _kAI_SI2_Source_SelectSame_As_SI 0
#define _kAI_SI2_Source_SelectINTIMEBASE1 1
         
#define _kAI_EXTMUX_CLK_Pulse_Width 7
#define _kAI_CONVERT_Pulse_Width 11
#define _kAI_EXTMUX_CLK_Pulse_Width45_Clock_Periods 0
#define _kAI_EXTMUX_CLK_Pulse_WidthEq_LOCALMUX_CLK_Pulse_Width 1
#define _kAI_CONVERT_Pulse_WidthAbout_2_Clock_Periods 0
#define _kAI_CONVERT_Pulse_WidthAbout_1_Clock_Period 1
         
#define _kAI_CONVERT_Output_Select 1
#define _kAI_EXTMUX_CLK_Output_Select 6
#define _kAI_SCAN_IN_PROG_Output_Select 7
#define _kAI_START_Output_Select 8
#define _kAI_CONVERT_Output_SelectHigh_Z 0
#define _kAI_CONVERT_Output_SelectGround 1
#define _kAI_CONVERT_Output_SelectActive_Low 2
#define _kAI_CONVERT_Output_SelectActive_High 3
#define _kAI_EXTMUX_CLK_Output_SelectHigh_Z 0
#define _kAI_EXTMUX_CLK_Output_SelectGround 1
#define _kAI_EXTMUX_CLK_Output_SelectActive_Low 2
#define _kAI_EXTMUX_CLK_Output_SelectActive_High 3
#define _kAI_SCAN_IN_PROG_Output_SelectHigh_Z 0
#define _kAI_SCAN_IN_PROG_Output_SelectGround 1
#define _kAI_SCAN_IN_PROG_Output_SelectActive_Low 2
#define _kAI_SCAN_IN_PROG_Output_SelectActive_High 3
#define _kAI_START_Output_SelectAD_START 0
#define _kAI_START_Output_SelectSCAN_IN_PROG 1
         
#define _kAI_START_Select 1
#define _kAI_START_Edge 2
#define _kAI_START_Sync 3
#define _kAI_STOP_Select 4
#define _kAI_STOP_Edge 5
#define _kAI_STOP_Sync 6
#define _kAI_STOP_Polarity 7
#define _kAI_START_Polarity 8
#define _kAI_START_SelectSI_TC 0
#define _kAI_START_SelectPFI0 1
#define _kAI_START_SelectPFI1 2
#define _kAI_START_SelectPFI2 3
#define _kAI_START_SelectPFI3 4
#define _kAI_START_SelectPFI4 5
#define _kAI_START_SelectPFI5 6
#define _kAI_START_SelectPFI6 7
#define _kAI_START_SelectPFI7 8
#define _kAI_START_SelectPFI8 9
#define _kAI_START_SelectPFI9 10
#define _kAI_START_SelectRTSI0 11
#define _kAI_START_SelectRTSI1 12
#define _kAI_START_SelectRTSI2 13
#define _kAI_START_SelectRTSI3 14
#define _kAI_START_SelectRTSI4 15
#define _kAI_START_SelectRTSI5 16
#define _kAI_START_SelectRTSI6 17
#define _kAI_START_SelectPulse 18
#define _kAI_START_SelectGPCtr0_Out 19
#define _kAI_START_SelectStar_Trigger 20
#define _kAI_START_SelectPFI10 21
#define _kAI_START_SelectPFI11 22
#define _kAI_START_SelectPFI12 23
#define _kAI_START_SelectPFI13 24
#define _kAI_START_SelectPFI14 25
#define _kAI_START_SelectPFI15 26
#define _kAI_START_SelectRTSI7 27
#define _kAI_START_SelectGPCtr1_Out 28
#define _kAI_START_SelectSCXI_Trig1 29
#define _kAI_START_SelectAnalog_Trigger 30
#define _kAI_START_SelectLow 31
#define _kAI_STOP_SelectDIV_TC_Or_Pulse 0
#define _kAI_STOP_SelectPFI0 1
#define _kAI_STOP_SelectPFI1 2
#define _kAI_STOP_SelectPFI2 3
#define _kAI_STOP_SelectPFI3 4
#define _kAI_STOP_SelectPFI4 5
#define _kAI_STOP_SelectPFI5 6
#define _kAI_STOP_SelectPFI6 7
#define _kAI_STOP_SelectPFI7 8
#define _kAI_STOP_SelectPFI8 9
#define _kAI_STOP_SelectPFI9 10
#define _kAI_STOP_SelectRTSI0 11
#define _kAI_STOP_SelectRTSI1 12
#define _kAI_STOP_SelectRTSI2 13
#define _kAI_STOP_SelectRTSI3 14
#define _kAI_STOP_SelectRTSI4 15
#define _kAI_STOP_SelectRTSI5 16
#define _kAI_STOP_SelectRTSI6 17
#define _kAI_STOP_SelectSI2TC 18
#define _kAI_STOP_SelectIN 19
#define _kAI_STOP_SelectStar_Trigger 20
#define _kAI_STOP_SelectPFI10 21
#define _kAI_STOP_SelectPFI11 22
#define _kAI_STOP_SelectPFI12 23
#define _kAI_STOP_SelectPFI13 24
#define _kAI_STOP_SelectPFI14 25
#define _kAI_STOP_SelectPFI15 26
#define _kAI_STOP_SelectRTSI7 27
#define _kAI_STOP_SelectAnalog_Trigger 30
#define _kAI_STOP_SelectLow 31
#define _kAI_STOP_PolarityActive_High_Or_Rising_Edge 0
#define _kAI_STOP_PolarityActive_Low_Or_Falling_Edge 1
#define _kAI_STOP_PolarityActive_High 0
#define _kAI_STOP_PolarityActive_Low 1
#define _kAI_STOP_PolarityRising_Edge 0
#define _kAI_STOP_PolarityFalling_Edge 1
#define _kAI_START_PolarityActive_High_Or_Rising_Edge 0
#define _kAI_START_PolarityActive_Low_Or_Falling_Edge 1
#define _kAI_START_PolarityActive_High 0
#define _kAI_START_PolarityActive_Low 1
#define _kAI_START_PolarityRising_Edge 0
#define _kAI_START_PolarityFalling_Edge 1
         
#define _kPass_Thru_0_Interrupt_St 1
#define _kAI_FIFO_Request_St 2
#define _kG0_Gate_Interrupt_St 3
#define _kG0_TC_St 4
#define _kAI_STOP_St 5
#define _kAI_START_St 6
#define _kAI_SC_TC_St 7
#define _kAI_START1_St 8
#define _kAI_START2_St 9
#define _kAI_SC_TC_Error_St 10
#define _kAI_Overflow_St 11
#define _kAI_Overrun_St 12
#define _kAI_FIFO_Empty_St 13
#define _kAI_FIFO_Half_Full_St 14
#define _kAI_FIFO_Full_St 15
#define _kInterrupt_Group_A_Status 16
         
#define _kAnalog_Trigger_Mode 1
#define _kAnalog_Trigger_Enable 2
#define _kAnalog_Trigger_Reset 4
#define _kMisc_Counter_TCs_Output_Enable 5
#define _kGPFO_1_Output_Select 6
#define _kGPFO_0_Output_Select 10
#define _kGPFO_0_Output_Enable 11
#define _kGPFO_1_Output_Enable 12
#define _kAnalog_Trigger_ModeLow_Window 0
#define _kAnalog_Trigger_ModeHigh_Window 1
#define _kAnalog_Trigger_ModeMiddle_Window 2
#define _kAnalog_Trigger_ModeHigh_Hysteresis 4
#define _kAnalog_Trigger_ModeLow_Hysteresis 6
#define _kAnalog_Trigger_EnableDisabled 0
#define _kAnalog_Trigger_EnableEnabled 1
#define _kGPFO_1_Output_SelectG_OUT 0
#define _kGPFO_1_Output_SelectDIV_TC 1
#define _kGPFO_0_Output_SelectG_OUT 0
#define _kGPFO_0_Output_SelectRTSI0 1
#define _kGPFO_0_Output_SelectRTSI1 2
#define _kGPFO_0_Output_SelectRTSI2 3
#define _kGPFO_0_Output_SelectRTSI3 4
#define _kGPFO_0_Output_SelectRTSI4 5
#define _kGPFO_0_Output_SelectRTSI5 6
#define _kGPFO_0_Output_SelectRTSI6 7
#define _kGPFO_0_Output_EnableInput 0
#define _kGPFO_0_Output_EnableOutput 1
#define _kGPFO_1_Output_EnableInput 0
#define _kGPFO_1_Output_EnableOutput 1
         
#define _kAI_START1_Select 1
#define _kAI_START1_Edge 2
#define _kAI_START1_Sync 3
#define _kAI_START2_Select 4
#define _kAI_START2_Edge 5
#define _kAI_START2_Sync 6
#define _kAI_START2_Polarity 7
#define _kAI_START1_Polarity 8
#define _kAI_START1_SelectPulse 0
#define _kAI_START1_SelectPFI0 1
#define _kAI_START1_SelectPFI1 2
#define _kAI_START1_SelectPFI2 3
#define _kAI_START1_SelectPFI3 4
#define _kAI_START1_SelectPFI4 5
#define _kAI_START1_SelectPFI5 6
#define _kAI_START1_SelectPFI6 7
#define _kAI_START1_SelectPFI7 8
#define _kAI_START1_SelectPFI8 9
#define _kAI_START1_SelectPFI9 10
#define _kAI_START1_SelectRTSI0 11
#define _kAI_START1_SelectRTSI1 12
#define _kAI_START1_SelectRTSI2 13
#define _kAI_START1_SelectRTSI3 14
#define _kAI_START1_SelectRTSI4 15
#define _kAI_START1_SelectRTSI5 16
#define _kAI_START1_SelectRTSI6 17
#define _kAI_START1_SelectGPCtr0_Out 18
#define _kAI_START1_SelectGPCtr1_Out 19
#define _kAI_START1_SelectStar_Trigger 20
#define _kAI_START1_SelectPFI10 21
#define _kAI_START1_SelectPFI11 22
#define _kAI_START1_SelectPFI12 23
#define _kAI_START1_SelectPFI13 24
#define _kAI_START1_SelectPFI14 25
#define _kAI_START1_SelectPFI15 26
#define _kAI_START1_SelectRTSI7 27
#define _kAI_START1_SelectAnalog_Trigger 30
#define _kAI_START1_SelectLow 31
#define _kAI_START2_SelectPulse 0
#define _kAI_START2_SelectPFI0 1
#define _kAI_START2_SelectPFI1 2
#define _kAI_START2_SelectPFI2 3
#define _kAI_START2_SelectPFI3 4
#define _kAI_START2_SelectPFI4 5
#define _kAI_START2_SelectPFI5 6
#define _kAI_START2_SelectPFI6 7
#define _kAI_START2_SelectPFI7 8
#define _kAI_START2_SelectPFI8 9
#define _kAI_START2_SelectPFI9 10
#define _kAI_START2_SelectRTSI0 11
#define _kAI_START2_SelectRTSI1 12
#define _kAI_START2_SelectRTSI2 13
#define _kAI_START2_SelectRTSI3 14
#define _kAI_START2_SelectRTSI4 15
#define _kAI_START2_SelectRTSI5 16
#define _kAI_START2_SelectRTSI6 17
#define _kAI_START2_SelectStar_Trigger 20
#define _kAI_START2_SelectPFI10 21
#define _kAI_START2_SelectPFI11 22
#define _kAI_START2_SelectPFI12 23
#define _kAI_START2_SelectPFI13 24
#define _kAI_START2_SelectPFI14 25
#define _kAI_START2_SelectPFI15 26
#define _kAI_START2_SelectRTSI7 27
#define _kAI_START2_SelectAnalog_Trigger 30
#define _kAI_START2_SelectLow 31
#define _kAI_START2_PolarityActive_High_Or_Rising_Edge 0
#define _kAI_START2_PolarityActive_Low_Or_Falling_Edge 1
#define _kAI_START2_PolarityActive_High 0
#define _kAI_START2_PolarityActive_Low 1
#define _kAI_START2_PolarityRising_Edge 0
#define _kAI_START2_PolarityFalling_Edge 1
#define _kAI_START1_PolarityActive_High_Or_Rising_Edge 0
#define _kAI_START1_PolarityActive_Low_Or_Falling_Edge 1
#define _kAI_START1_PolarityActive_High 0
#define _kAI_START1_PolarityActive_Low 1
#define _kAI_START1_PolarityRising_Edge 0
#define _kAI_START1_PolarityFalling_Edge 1
         
#define _kAO_START1_Pulse 1
#define _kAO_Mute_A 3
#define _kAO_Mute_B 4
#define _kAO_BC_Switch_Load_On_TC 5
#define _kAO_UC_Switch_Load_On_TC 6
#define _kAO_UC_Switch_Load_On_BC_TC 7
#define _kAO_UI_Switch_Load_On_TC 8
#define _kAO_UI_Switch_Load_On_Stop 9
#define _kAO_UI_Switch_Load_On_BC_TC 10
#define _kAO_BC_Save_Trace 11
#define _kAO_BC_Gate_Enable 12
#define _kAO_UC_Save_Trace 13
#define _kAO_Start_Stop_Gate_Enable 14
#define _kAO_End_On_UC_TC 15
#define _kAO_End_On_BC_TC 16
         
#define _kAO_UPDATE_Pulse 1
#define _kAO_DAC0_Update_Mode 3
#define _kAO_DAC1_Update_Mode 5
#define _kAO_BC_Load 6
#define _kAO_BC_Arm 7
#define _kAO_UC_Load 8
#define _kAO_UC_Arm 9
#define _kAO_UI_Load 10
#define _kAO_UI_Arm 11
#define _kAO_Disarm 14
#define _kAO_START_Pulse 15
#define _kAO_Analog_Trigger_Reset 16
#define _kAO_DAC0_Update_ModeImmediate 0
#define _kAO_DAC0_Update_ModeTimed 1
#define _kAO_DAC1_Update_ModeImmediate 0
#define _kAO_DAC1_Update_ModeTimed 1
         
#define _kAO_Trigger_Once 1
#define _kAO_Continuous 2
#define _kAO_UC_Switch_Load_Every_TC 3
#define _kAO_UI_Source_Polarity 4
#define _kAO_UPDATE_Source_Polarity 5
#define _kAO_Multiple_Channels 6
#define _kAO_UI_Source_Select 7
#define _kAO_UPDATE_Source_Select 8
#define _kAO_ContinuousStop_On_BC_TC 0
#define _kAO_ContinuousIgnore_BC_TC 1
#define _kAO_UI_Source_PolarityRising_Edge 0
#define _kAO_UI_Source_PolarityFalling_Edge 1
#define _kAO_UPDATE_Source_PolarityRising_Edge 0
#define _kAO_UPDATE_Source_PolarityFalling_Edge 1
#define _kAO_UI_Source_SelectGround 0
#define _kAO_UI_Source_SelectPFI0 1
#define _kAO_UI_Source_SelectPFI1 2
#define _kAO_UI_Source_SelectPFI2 3
#define _kAO_UI_Source_SelectPFI3 4
#define _kAO_UI_Source_SelectPFI4 5
#define _kAO_UI_Source_SelectPFI5 6
#define _kAO_UI_Source_SelectPFI6 7
#define _kAO_UI_Source_SelectPFI7 8
#define _kAO_UI_Source_SelectPFI8 9
#define _kAO_UI_Source_SelectPFI9 10
#define _kAO_UI_Source_SelectRTSI0 11
#define _kAO_UI_Source_SelectRTSI1 12
#define _kAO_UI_Source_SelectRTSI2 13
#define _kAO_UI_Source_SelectRTSI3 14
#define _kAO_UI_Source_SelectRTSI4 15
#define _kAO_UI_Source_SelectRTSI5 16
#define _kAO_UI_Source_SelectRTSI6 17
#define _kAO_UI_Source_SelectIN_TIMEBASE2 19
#define _kAO_UI_Source_SelectStar_Trigger 20
#define _kAO_UI_Source_SelectPFI10 21
#define _kAO_UI_Source_SelectPFI11 22
#define _kAO_UI_Source_SelectPFI12 23
#define _kAO_UI_Source_SelectPFI13 24
#define _kAO_UI_Source_SelectPFI14 25
#define _kAO_UI_Source_SelectPFI15 26
#define _kAO_UI_Source_SelectRTSI7 27
#define _kAO_UI_Source_SelectAO_IN_TIMEBASE1 28
#define _kAO_UI_Source_SelectPXI_Clk10 29
#define _kAO_UI_Source_SelectAnalog_Trigger 30
#define _kAO_UI_Source_SelectLow 31
#define _kAO_UPDATE_Source_SelectUI_TC 0
#define _kAO_UPDATE_Source_SelectPFI0 1
#define _kAO_UPDATE_Source_SelectPFI1 2
#define _kAO_UPDATE_Source_SelectPFI2 3
#define _kAO_UPDATE_Source_SelectPFI3 4
#define _kAO_UPDATE_Source_SelectPFI4 5
#define _kAO_UPDATE_Source_SelectPFI5 6
#define _kAO_UPDATE_Source_SelectPFI6 7
#define _kAO_UPDATE_Source_SelectPFI7 8
#define _kAO_UPDATE_Source_SelectPFI8 9
#define _kAO_UPDATE_Source_SelectPFI9 10
#define _kAO_UPDATE_Source_SelectRTSI0 11
#define _kAO_UPDATE_Source_SelectRTSI1 12
#define _kAO_UPDATE_Source_SelectRTSI2 13
#define _kAO_UPDATE_Source_SelectRTSI3 14
#define _kAO_UPDATE_Source_SelectRTSI4 15
#define _kAO_UPDATE_Source_SelectRTSI5 16
#define _kAO_UPDATE_Source_SelectRTSI6 17
#define _kAO_UPDATE_Source_SelectGPCTR0_Out 18
#define _kAO_UPDATE_Source_SelectGPCTR1_Out 19
#define _kAO_UPDATE_Source_SelectStar_Trigger 20
#define _kAO_UPDATE_Source_SelectPFI10 21
#define _kAO_UPDATE_Source_SelectPFI11 22
#define _kAO_UPDATE_Source_SelectPFI12 23
#define _kAO_UPDATE_Source_SelectPFI13 24
#define _kAO_UPDATE_Source_SelectPFI14 25
#define _kAO_UPDATE_Source_SelectPFI15 26
#define _kAO_UPDATE_Source_SelectRTSI7 27
#define _kAO_UPDATE_Source_SelectAnalog_Trigger 30
#define _kAO_UPDATE_Source_SelectLow 31
         
#define _kAO_BC_Write_Switch 1
#define _kAO_BC_Reload_Mode 2
#define _kAO_BC_Initial_Load_Source 3
#define _kAO_UI_Write_Switch 4
#define _kAO_UI_Reload_Mode 5
#define _kAO_UI_Initial_Load_Source 6
#define _kAO_UC_Write_Switch 9
#define _kAO_UC_Initial_Load_Source 10
#define _kAO_START1_Disable 11
#define _kAO_FIFO_Retransmit_Enable 12
#define _kAO_FIFO_Mode 13
#define _kAO_BC_Initial_Load_SourceReg_A 0
#define _kAO_BC_Initial_Load_SourceReg_B 1
#define _kAO_UI_Reload_ModeNo_Change 0
#define _kAO_UI_Reload_ModeAlternate_On_STOP 4
#define _kAO_UI_Reload_ModeSwitch_On_STOP 5
#define _kAO_UI_Reload_ModeAlternate_On_BC_TC 6
#define _kAO_UI_Reload_ModeSwitch_On_BC_TC 7
#define _kAO_UI_Initial_Load_SourceReg_A 0
#define _kAO_UI_Initial_Load_SourceReg_B 1
#define _kAO_UC_Initial_Load_SourceReg_A 0
#define _kAO_UC_Initial_Load_SourceReg_B 1
#define _kAO_FIFO_ModeEmpty 0
#define _kAO_FIFO_ModeLess_Than_Half_Full 1
#define _kAO_FIFO_ModeLess_Than_Full 2
#define _kAO_FIFO_ModeLess_Than_Half_Full_to_Full 3
         
#define _kAO_UPDATE_Output_Select 1
#define _kAO_External_Gate_Polarity 3
#define _kAO_Number_Of_Channels 5
#define _kAO_External_Gate_Select 6
#define _kAO_External_Gate_Enable 7
#define _kAO_UPDATE_Output_SelectHigh_Z 0
#define _kAO_UPDATE_Output_SelectGround 1
#define _kAO_UPDATE_Output_SelectActive_Low 2
#define _kAO_UPDATE_Output_SelectActive_High 3
#define _kAO_External_Gate_PolarityActive_High 0
#define _kAO_External_Gate_PolarityActive_Low 1
#define _kAO_External_Gate_SelectDisabled 0
#define _kAO_External_Gate_SelectPFI0 1
#define _kAO_External_Gate_SelectPFI1 2
#define _kAO_External_Gate_SelectPFI2 3
#define _kAO_External_Gate_SelectPFI3 4
#define _kAO_External_Gate_SelectPFI4 5
#define _kAO_External_Gate_SelectPFI5 6
#define _kAO_External_Gate_SelectPFI6 7
#define _kAO_External_Gate_SelectPFI7 8
#define _kAO_External_Gate_SelectPFI8 9
#define _kAO_External_Gate_SelectPFI9 10
#define _kAO_External_Gate_SelectRTSI0 11
#define _kAO_External_Gate_SelectRTSI1 12
#define _kAO_External_Gate_SelectRTSI2 13
#define _kAO_External_Gate_SelectRTSI3 14
#define _kAO_External_Gate_SelectRTSI4 15
#define _kAO_External_Gate_SelectRTSI5 16
#define _kAO_External_Gate_SelectRTSI6 17
#define _kAO_External_Gate_SelectStar_Trigger 20
#define _kAO_External_Gate_SelectPFI10 21
#define _kAO_External_Gate_SelectPFI11 22
#define _kAO_External_Gate_SelectPFI12 23
#define _kAO_External_Gate_SelectPFI13 24
#define _kAO_External_Gate_SelectPFI14 25
#define _kAO_External_Gate_SelectPFI15 26
#define _kAO_External_Gate_SelectRTSI7 27
#define _kAO_External_Gate_SelectAnalog_Trigger 30
#define _kAO_External_Gate_SelectLow 31
         
#define _kAO_Last_Gate_Disable 1
#define _kAO_Software_Gate 2
#define _kAO_Not_An_UPDATE 3
#define _kAO_Stop_On_BC_TC_Error 4
#define _kAO_Stop_On_BC_TC_Trigger_Error 5
#define _kAO_Stop_On_Overrun_Error 6
#define _kAO_Trigger_Length 12
#define _kAO_UC_Switch_Load_Every_BC_TC 13
#define _kAO_Trigger_LengthDA_START1 0
#define _kAO_Trigger_LengthDA_ST1ED 1
         
#define _kAO_Interval_Buffer_Mode 4
#define _kAO_BC_Source_Select 5
#define _kAO_UPDATE_Pulse_Width 6
#define _kAO_UPDATE_Pulse_Timebase 7
#define _kAO_UPDATE_Original_Pulse 8
#define _kAO_FIFO_Enable 11
#define _kAO_TMRDACWR_Pulse_Width 13
#define _kAO_Number_Of_DAC_Packages 15
#define _kAO_Multiple_DACS_Per_Package 16
#define _kAO_BC_Source_SelectUPDATE 0
#define _kAO_BC_Source_SelectUC_TC 1
#define _kAO_UPDATE_Pulse_WidthAbout_1_TIMEBASE_Periods 0
#define _kAO_UPDATE_Pulse_WidthAbout_3_TIMEBASE_Periods 1
#define _kAO_UPDATE_Pulse_TimebaseSelect_By_PulseWidth 0
#define _kAO_UPDATE_Pulse_TimebaseSelect_By_OriginalPulse 1
#define _kAO_UPDATE_Original_PulseMax_Of_UPDATE_Pulsewidth 0
#define _kAO_UPDATE_Original_PulseEqual_To_UPDATE_Pulsewidth 1
#define _kAO_TMRDACWR_Pulse_WidthAbout_3_TIMEBASE_Periods 0
#define _kAO_TMRDACWR_Pulse_WidthAbout_2_TIMEBASE_Periods 1
#define _kAO_Number_Of_DAC_PackagesDual_DAC_mode 0
#define _kAO_Number_Of_DAC_PackagesSingle_DAC_mode 1
         
#define _kAO_START_Edge 2
#define _kAO_START_Sync 3
#define _kAO_AOFREQ_Enable 5
#define _kAO_START_Polarity 6
#define _kPulse 0
#define _kPFI0 1
#define _kPFI1 2
#define _kPFI2 3
#define _kPFI3 4
#define _kPFI4 5
#define _kPFI5 6
#define _kPFI6 7
#define _kPFI7 8
#define _kPFI8 9
#define _kPFI9 10
#define _kRTSI0 11
#define _kRTSI1 12
#define _kRTSI2 13
#define _kRTSI3 14
#define _kRTSI4 15
#define _kRTSI5 16
#define _kRTSI6 17
#define _kLow 31
#define _kAO_START_PolarityActive_High_Or_Rising_Edge 0
#define _kAO_START_PolarityActive_Low_Or_Falling_Edge 1
#define _kAO_START_PolarityActive_High 0
#define _kAO_START_PolarityActive_Low 1
#define _kAO_START_PolarityRising_Edge 0
#define _kAO_START_PolarityFalling_Edge 1
         
#define _kAO_BC_Armed_St 1
#define _kAO_BC_Save_St 3
#define _kAO_BC_Q_St 4
#define _kAO_BC_TC_Trigger_Error_St 5
#define _kAO_UI_Armed_St 6
#define _kAO_UI_Next_Load_Source_St 7
#define _kAO_UC_Save_St 8
#define _kAO_UI_Count_Enabled_St 9
#define _kAO_UI_Q_St 10
#define _kAO_UC_Armed_St 15
         
#define _kPass_Thru_1_Interrupt_St 1
#define _kAO_FIFO_Request_St 2
#define _kG1_Gate_Interrupt_St 3
#define _kG1_TC_St 4
#define _kAO_UPDATE_St 6
#define _kAO_UC_TC_St 7
#define _kAO_BC_TC_St 8
#define _kAO_START1_St 9
#define _kAO_Overrun_St 10
#define _kAO_START_St 11
#define _kAO_BC_TC_Error_St 12
#define _kAO_FIFO_Empty_St 13
#define _kAO_FIFO_Half_Full_St 14
#define _kAO_FIFO_Full_St 15
#define _kInterrupt_Group_B_Status 16
         
#define _kAO_START1_Select 1
#define _kAO_START1_Edge 2
#define _kAO_START1_Sync 3
#define _kAO_START1_Polarity 6
#define _kAO_Delayed_START1 7
#define _kAO_START1_SelectPulse 0
#define _kAO_START1_SelectPFI0 1
#define _kAO_START1_SelectPFI1 2
#define _kAO_START1_SelectPFI2 3
#define _kAO_START1_SelectPFI3 4
#define _kAO_START1_SelectPFI4 5
#define _kAO_START1_SelectPFI5 6
#define _kAO_START1_SelectPFI6 7
#define _kAO_START1_SelectPFI7 8
#define _kAO_START1_SelectPFI8 9
#define _kAO_START1_SelectPFI9 10
#define _kAO_START1_SelectRTSI0 11
#define _kAO_START1_SelectRTSI1 12
#define _kAO_START1_SelectRTSI2 13
#define _kAO_START1_SelectRTSI3 14
#define _kAO_START1_SelectRTSI4 15
#define _kAO_START1_SelectRTSI5 16
#define _kAO_START1_SelectRTSI6 17
#define _kAO_START1_SelectAI_START_2 18
#define _kAO_START1_SelectAI_START_1 19
#define _kAO_START1_SelectStar_Trigger 20
#define _kAO_START1_SelectPFI10 21
#define _kAO_START1_SelectPFI11 22
#define _kAO_START1_SelectPFI12 23
#define _kAO_START1_SelectPFI13 24
#define _kAO_START1_SelectPFI14 25
#define _kAO_START1_SelectPFI15 26
#define _kAO_START1_SelectRTSI7 27
#define _kAO_START1_SelectAnalog_Trigger 30
#define _kAO_START1_SelectLow 31
#define _kAO_START1_PolarityActive_High 0
#define _kAO_START1_PolarityRising_Edge 0
#define _kAO_START1_PolarityActive_Low 1
#define _kAO_START1_PolarityFalling_Edge 1
         
#define _kFOUT_Divider 1
#define _kClock_To_Board 6
#define _kClock_To_Board_Divide_By_2 7
#define _kSlow_Internal_Timebase 9
#define _kDIO_Serial_Out_Divide_By_2 11
#define _kFOUT_Timebase_Select 12
#define _kFOUT_Enable 13
         
#define _kG0_Gate_Error_Confirm 6
#define _kG0_TC_Error_Confirm 7
#define _kAI_SC_TC_Error_Confirm 8
#define _kAI_SC_TC_Interrupt_Ack 9
#define _kAI_START1_Interrupt_Ack 10
#define _kAI_START2_Interrupt_Ack 11
#define _kAI_START_Interrupt_Ack 12
#define _kAI_STOP_Interrupt_Ack 13
#define _kAI_Error_Interrupt_Ack 14
#define _kG0_TC_Interrupt_Ack 15
#define _kG0_Gate_Interrupt_Ack 16
         
#define _kAI_SC_TC_Interrupt_Enable 1
#define _kAI_START1_Interrupt_Enable 2
#define _kAI_START2_Interrupt_Enable 3
#define _kAI_START_Interrupt_Enable 4
#define _kAI_STOP_Interrupt_Enable 5
#define _kAI_Error_Interrupt_Enable 6
#define _kG0_TC_Interrupt_Enable 7
#define _kAI_FIFO_Interrupt_Enable 8
#define _kG0_Gate_Interrupt_Enable 9
         
#define _kG1_Gate_Error_Confirm 2
#define _kG1_TC_Error_Confirm 3
#define _kAO_BC_TC_Trigger_Error_Confirm 4
#define _kAO_BC_TC_Error_Confirm 5
#define _kAO_UC_TC_Interrupt_Ack 8
#define _kAO_BC_TC_Interrupt_Ack 9
#define _kAO_START1_Interrupt_Ack 10
#define _kAO_UPDATE_Interrupt_Ack 11
#define _kAO_START_Interrupt_Ack 12
#define _kAO_STOP_Interrupt_Ack 13
#define _kAO_Error_Interrupt_Ack 14
#define _kG1_TC_Interrupt_Ack 15
#define _kG1_Gate_Interrupt_Ack 16
         
#define _kInterrupt_Group_A_Enable 10
#define _kInterrupt_Group_B_Enable 12
         
#define _kAO_BC_TC_Interrupt_Enable 1
#define _kAO_START1_Interrupt_Enable 2
#define _kAO_UPDATE_Interrupt_Enable 3
#define _kAO_START_Interrupt_Enable 4
#define _kAO_STOP_Interrupt_Enable 5
#define _kAO_Error_Interrupt_Enable 6
#define _kAO_UC_TC_Interrupt_Enable 7
#define _kAO_FIFO_Interrupt_Enable 9
#define _kG1_TC_Interrupt_Enable 10
#define _kG1_Gate_Interrupt_Enable 11
#define _kPass_Thru_1_Interrupt_Enable 12
         
#define _kPFI0_Pin_Dir 1
#define _kPFI1_Pin_Dir 2
#define _kPFI2_Pin_Dir 3
#define _kPFI3_Pin_Dir 4
#define _kPFI4_Pin_Dir 5
#define _kPFI5_Pin_Dir 6
#define _kPFI6_Pin_Dir 7
#define _kPFI7_Pin_Dir 8
#define _kPFI8_Pin_Dir 9
#define _kPFI9_Pin_Dir 10
#define _kPFI10_Pin_Dir 11
#define _kPFI11_Pin_Dir 12
#define _kPFI12_Pin_Dir 13
#define _kPFI13_Pin_Dir 14
#define _kPFI14_Pin_Dir 15
#define _kPFI15_Pin_Dir 16
#define _kPFI0_Pin_DirInput 0
#define _kPFI0_Pin_DirOutput 1
#define _kPFI1_Pin_DirInput 0
#define _kPFI1_Pin_DirOutput 1
#define _kPFI2_Pin_DirInput 0
#define _kPFI2_Pin_DirOutput 1
#define _kPFI3_Pin_DirInput 0
#define _kPFI3_Pin_DirOutput 1
#define _kPFI4_Pin_DirInput 0
#define _kPFI4_Pin_DirOutput 1
#define _kPFI5_Pin_DirInput 0
#define _kPFI5_Pin_DirOutput 1
#define _kPFI6_Pin_DirInput 0
#define _kPFI6_Pin_DirOutput 1
#define _kPFI7_Pin_DirInput 0
#define _kPFI7_Pin_DirOutput 1
#define _kPFI8_Pin_DirInput 0
#define _kPFI8_Pin_DirOutput 1
#define _kPFI9_Pin_DirInput 0
#define _kPFI9_Pin_DirOutput 1
#define _kPFI10_Pin_DirInput 0
#define _kPFI10_Pin_DirOutput 1
#define _kPFI11_Pin_DirInput 0
#define _kPFI11_Pin_DirOutput 1
#define _kPFI12_Pin_DirInput 0
#define _kPFI12_Pin_DirOutput 1
#define _kPFI13_Pin_DirInput 0
#define _kPFI13_Pin_DirOutput 1
#define _kPFI14_Pin_DirInput 0
#define _kPFI14_Pin_DirOutput 1
#define _kPFI15_Pin_DirInput 0
#define _kPFI15_Pin_DirOutput 1
         
#define _kAI_Reset 1
#define _kAO_Reset 2
#define _kG0_Reset 3
#define _kG1_Reset 4
#define _kAI_Configuration_Start 5
#define _kAO_Configuration_Start 6
#define _kAI_Configuration_End 9
#define _kAO_Configuration_End 10
#define _kSoftware_Reset 12
         
#define _kG0_Output_St 1
#define _kG1_Output_St 2
#define _kAO_STOP_St 3
#define _kAI_EOC_St 5
#define _kAO_TMRDACWRs_In_Progress_St 6
#define _kAI_Config_Memory_Empty_St 7
#define _kAI_Scan_In_Progress_St 8
#define _kGeneric_Status 9
#define _kG0_HW_Save_St 10
#define _kG1_HW_Save_St 11
#define _kG0_Permanent_Stale_Data_St 12
#define _kG1_Permanent_Stale_Data_St 13
#define _kG0_Output_StLow 0
#define _kG0_Output_StHigh 1
#define _kG1_Output_StLow 0
#define _kG1_Output_StHigh 1
#define _kG0_HW_Save_StTracing 0
#define _kG0_HW_Save_StLatched 1
#define _kG1_HW_Save_StTracing 0
#define _kG1_HW_Save_StLatched 1
#define _kG0_Permanent_Stale_Data_StNo_Error 0
#define _kG0_Permanent_Stale_Data_StError 1
#define _kG1_Permanent_Stale_Data_StNo_Error 0
#define _kG1_Permanent_Stale_Data_StError 1
         
#define _kG0_Bank_St 1
#define _kG1_Bank_St 2
#define _kG0_Gate_St 3
#define _kG1_Gate_St 4
#define _kAI_SC_Gate_St 5
#define _kAI_Start_Stop_Gate_St 6
#define _kAO_BC_Gate_St 7
#define _kAO_Start_Stop_Gate_St 8
#define _kAI_SI2_Q_St 9
#define _kAI_External_Gate_St 10
#define _kAO_External_Gate_St 11
#define _kDIO_Serial_IO_In_Progress_St 12
#define _kAO_UC_Q_St 14
#define _kAI_Last_Shiftin_St 15
#define _kG0_Bank_StBank_X 0
#define _kG0_Bank_StBank_Y 1
#define _kG1_Bank_StBank_X 0
#define _kG1_Bank_StBank_Y 1
#define _kG0_Gate_StInactive 0
#define _kG0_Gate_StActive 1
#define _kG1_Gate_StInactive 0
#define _kG1_Gate_StActive 1
         
#define _kRTSI_Shared_MUX_0_Output_Select 1
#define _kRTSI_Shared_MUX_1_Output_Select 2
#define _kRTSI_Shared_MUX_2_Output_Select 3
#define _kRTSI_Shared_MUX_3_Output_Select 4
#define _kRTSI_Shared_MUX_0_Output_SelectMUX_Out_Sel_PFI0 0
#define _kRTSI_Shared_MUX_0_Output_SelectMUX_Out_Sel_PFI1 1
#define _kRTSI_Shared_MUX_0_Output_SelectMUX_Out_Sel_PFI2 2
#define _kRTSI_Shared_MUX_0_Output_SelectMUX_Out_Sel_PFI3 3
#define _kRTSI_Shared_MUX_0_Output_SelectMUX_Out_Sel_PFI4 4
#define _kRTSI_Shared_MUX_0_Output_SelectMUX_Out_Sel_PFI5 5
#define _kRTSI_Shared_MUX_0_Output_SelectMUX_Out_Sel_AO_Gate_RTSI 6
#define _kRTSI_Shared_MUX_0_Output_SelectMUX_Out_Sel_AI_Gate_RTSI 7
#define _kRTSI_Shared_MUX_0_Output_SelectMUX_Out_Sel_Freq_Out 8
#define _kRTSI_Shared_MUX_0_Output_SelectMUX_Out_Sel_G1_Out 9
#define _kRTSI_Shared_MUX_0_Output_SelectMUX_Out_Sel_G1_Selected_Gate 10
#define _kRTSI_Shared_MUX_0_Output_SelectMUX_Out_Sel_G1_Selected_Source 11
#define _kRTSI_Shared_MUX_0_Output_SelectMUX_Out_Sel_G1_Z 12
#define _kRTSI_Shared_MUX_0_Output_SelectMUX_Out_Sel_G0_Z 13
#define _kRTSI_Shared_MUX_0_Output_SelectMUX_Out_Sel_Analog_Trigger 14
#define _kRTSI_Shared_MUX_0_Output_SelectMUX_Out_Sel_AI_Start_Pulse 15
#define _kRTSI_Shared_MUX_1_Output_SelectMUX_Out_Sel_PFI0 0
#define _kRTSI_Shared_MUX_1_Output_SelectMUX_Out_Sel_PFI1 1
#define _kRTSI_Shared_MUX_1_Output_SelectMUX_Out_Sel_PFI2 2
#define _kRTSI_Shared_MUX_1_Output_SelectMUX_Out_Sel_PFI3 3
#define _kRTSI_Shared_MUX_1_Output_SelectMUX_Out_Sel_PFI4 4
#define _kRTSI_Shared_MUX_1_Output_SelectMUX_Out_Sel_PFI5 5
#define _kRTSI_Shared_MUX_1_Output_SelectMUX_Out_Sel_AO_Gate_RTSI 6
#define _kRTSI_Shared_MUX_1_Output_SelectMUX_Out_Sel_AI_Gate_RTSI 7
#define _kRTSI_Shared_MUX_1_Output_SelectMUX_Out_Sel_Freq_Out 8
#define _kRTSI_Shared_MUX_1_Output_SelectMUX_Out_Sel_G1_Out 9
#define _kRTSI_Shared_MUX_1_Output_SelectMUX_Out_Sel_G1_Selected_Gate 10
#define _kRTSI_Shared_MUX_1_Output_SelectMUX_Out_Sel_G1_Selected_Source 11
#define _kRTSI_Shared_MUX_1_Output_SelectMUX_Out_Sel_G1_Z 12
#define _kRTSI_Shared_MUX_1_Output_SelectMUX_Out_Sel_G0_Z 13
#define _kRTSI_Shared_MUX_1_Output_SelectMUX_Out_Sel_Analog_Trigger 14
#define _kRTSI_Shared_MUX_1_Output_SelectMUX_Out_Sel_AI_Start_Pulse 15
#define _kRTSI_Shared_MUX_2_Output_SelectMUX_Out_Sel_PFI0 0
#define _kRTSI_Shared_MUX_2_Output_SelectMUX_Out_Sel_PFI1 1
#define _kRTSI_Shared_MUX_2_Output_SelectMUX_Out_Sel_PFI2 2
#define _kRTSI_Shared_MUX_2_Output_SelectMUX_Out_Sel_PFI3 3
#define _kRTSI_Shared_MUX_2_Output_SelectMUX_Out_Sel_PFI4 4
#define _kRTSI_Shared_MUX_2_Output_SelectMUX_Out_Sel_PFI5 5
#define _kRTSI_Shared_MUX_2_Output_SelectMUX_Out_Sel_AO_Gate_RTSI 6
#define _kRTSI_Shared_MUX_2_Output_SelectMUX_Out_Sel_AI_Gate_RTSI 7
#define _kRTSI_Shared_MUX_2_Output_SelectMUX_Out_Sel_Freq_Out 8
#define _kRTSI_Shared_MUX_2_Output_SelectMUX_Out_Sel_G1_Out 9
#define _kRTSI_Shared_MUX_2_Output_SelectMUX_Out_Sel_G1_Selected_Gate 10
#define _kRTSI_Shared_MUX_2_Output_SelectMUX_Out_Sel_G1_Selected_Source 11
#define _kRTSI_Shared_MUX_2_Output_SelectMUX_Out_Sel_G1_Z 12
#define _kRTSI_Shared_MUX_2_Output_SelectMUX_Out_Sel_G0_Z 13
#define _kRTSI_Shared_MUX_2_Output_SelectMUX_Out_Sel_Analog_Trigger 14
#define _kRTSI_Shared_MUX_2_Output_SelectMUX_Out_Sel_AI_Start_Pulse 15
#define _kRTSI_Shared_MUX_3_Output_SelectMUX_Out_Sel_PFI0 0
#define _kRTSI_Shared_MUX_3_Output_SelectMUX_Out_Sel_PFI1 1
#define _kRTSI_Shared_MUX_3_Output_SelectMUX_Out_Sel_PFI2 2
#define _kRTSI_Shared_MUX_3_Output_SelectMUX_Out_Sel_PFI3 3
#define _kRTSI_Shared_MUX_3_Output_SelectMUX_Out_Sel_PFI4 4
#define _kRTSI_Shared_MUX_3_Output_SelectMUX_Out_Sel_PFI5 5
#define _kRTSI_Shared_MUX_3_Output_SelectMUX_Out_Sel_AO_Gate_RTSI 6
#define _kRTSI_Shared_MUX_3_Output_SelectMUX_Out_Sel_AI_Gate_RTSI 7
#define _kRTSI_Shared_MUX_3_Output_SelectMUX_Out_Sel_Freq_Out 8
#define _kRTSI_Shared_MUX_3_Output_SelectMUX_Out_Sel_G1_Out 9
#define _kRTSI_Shared_MUX_3_Output_SelectMUX_Out_Sel_G1_Selected_Gate 10
#define _kRTSI_Shared_MUX_3_Output_SelectMUX_Out_Sel_G1_Selected_Source 11
#define _kRTSI_Shared_MUX_3_Output_SelectMUX_Out_Sel_G1_Z 12
#define _kRTSI_Shared_MUX_3_Output_SelectMUX_Out_Sel_G0_Z 13
#define _kRTSI_Shared_MUX_3_Output_SelectMUX_Out_Sel_Analog_Trigger 14
#define _kRTSI_Shared_MUX_3_Output_SelectMUX_Out_Sel_AI_Start_Pulse 15
         
#define _kRTSI0_Output_Select 1
#define _kRTSI1_Output_Select 2
#define _kRTSI2_Output_Select 3
#define _kRTSI3_Output_Select 4
#define _kRTSI0_Output_SelectADR_START1 0
#define _kRTSI0_Output_SelectADR_START2 1
#define _kRTSI0_Output_SelectSCLKG 2
#define _kRTSI0_Output_SelectDACUPDN 3
#define _kRTSI0_Output_SelectDA_START1 4
#define _kRTSI0_Output_SelectG_SRC_0 5
#define _kRTSI0_Output_SelectG_GATE_0 6
#define _kRTSI0_Output_SelectRGOUT0 7
#define _kRTSI0_Output_SelectRTSI_BRD_0 8
#define _kRTSI0_Output_SelectRTSI_BRD_1 9
#define _kRTSI0_Output_SelectRTSI_BRD_2 10
#define _kRTSI0_Output_SelectRTSI_BRD_3 11
#define _kRTSI0_Output_SelectRTSI_OSC 12
#define _kRTSI1_Output_SelectADR_START1 0
#define _kRTSI1_Output_SelectADR_START2 1
#define _kRTSI1_Output_SelectSCLKG 2
#define _kRTSI1_Output_SelectDACUPDN 3
#define _kRTSI1_Output_SelectDA_START1 4
#define _kRTSI1_Output_SelectG_SRC_0 5
#define _kRTSI1_Output_SelectG_GATE_0 6
#define _kRTSI1_Output_SelectRGOUT0 7
#define _kRTSI1_Output_SelectRTSI_BRD_0 8
#define _kRTSI1_Output_SelectRTSI_BRD_1 9
#define _kRTSI1_Output_SelectRTSI_BRD_2 10
#define _kRTSI1_Output_SelectRTSI_BRD_3 11
#define _kRTSI1_Output_SelectRTSI_OSC 12
#define _kRTSI2_Output_SelectADR_START1 0
#define _kRTSI2_Output_SelectADR_START2 1
#define _kRTSI2_Output_SelectSCLKG 2
#define _kRTSI2_Output_SelectDACUPDN 3
#define _kRTSI2_Output_SelectDA_START1 4
#define _kRTSI2_Output_SelectG_SRC_0 5
#define _kRTSI2_Output_SelectG_GATE_0 6
#define _kRTSI2_Output_SelectRGOUT0 7
#define _kRTSI2_Output_SelectRTSI_BRD_0 8
#define _kRTSI2_Output_SelectRTSI_BRD_1 9
#define _kRTSI2_Output_SelectRTSI_BRD_2 10
#define _kRTSI2_Output_SelectRTSI_BRD_3 11
#define _kRTSI2_Output_SelectRTSI_OSC 12
#define _kRTSI3_Output_SelectADR_START1 0
#define _kRTSI3_Output_SelectADR_START2 1
#define _kRTSI3_Output_SelectSCLKG 2
#define _kRTSI3_Output_SelectDACUPDN 3
#define _kRTSI3_Output_SelectDA_START1 4
#define _kRTSI3_Output_SelectG_SRC_0 5
#define _kRTSI3_Output_SelectG_GATE_0 6
#define _kRTSI3_Output_SelectRGOUT0 7
#define _kRTSI3_Output_SelectRTSI_BRD_0 8
#define _kRTSI3_Output_SelectRTSI_BRD_1 9
#define _kRTSI3_Output_SelectRTSI_BRD_2 10
#define _kRTSI3_Output_SelectRTSI_BRD_3 11
#define _kRTSI3_Output_SelectRTSI_OSC 12
         
#define _kDrive_RTSI_OSC 1
#define _kUse_RTSI_OSC 2
#define _kRTSI_Sub_Selection_1 3
#define _kRTSI0_Pin_Dir 9
#define _kRTSI1_Pin_Dir 10
#define _kRTSI2_Pin_Dir 11
#define _kRTSI3_Pin_Dir 12
#define _kRTSI4_Pin_Dir 13
#define _kRTSI5_Pin_Dir 14
#define _kRTSI6_Pin_Dir 15
#define _kRTSI7_Pin_Dir 16
#define _kRTSI_Sub_Selection_1G_OUT_0 0
#define _kRTSI_Sub_Selection_1G_OUT_0_RTSI_IO_Pin 1
#define _kRTSI0_Pin_DirInput 0
#define _kRTSI0_Pin_DirOutput 1
#define _kRTSI1_Pin_DirInput 0
#define _kRTSI1_Pin_DirOutput 1
#define _kRTSI2_Pin_DirInput 0
#define _kRTSI2_Pin_DirOutput 1
#define _kRTSI3_Pin_DirInput 0
#define _kRTSI3_Pin_DirOutput 1
#define _kRTSI4_Pin_DirInput 0
#define _kRTSI4_Pin_DirOutput 1
#define _kRTSI5_Pin_DirInput 0
#define _kRTSI5_Pin_DirOutput 1
#define _kRTSI6_Pin_DirInput 0
#define _kRTSI6_Pin_DirOutput 1
#define _kRTSI7_Pin_DirInput 0
#define _kRTSI7_Pin_DirOutput 1
         
#define _kRTSI4_Output_Select 1
#define _kRTSI5_Output_Select 2
#define _kRTSI6_Output_Select 3
#define _kRTSI7_Output_Select 4
#define _kRTSI4_Output_SelectADR_START1 0
#define _kRTSI4_Output_SelectADR_START2 1
#define _kRTSI4_Output_SelectSCLKG 2
#define _kRTSI4_Output_SelectDACUPDN 3
#define _kRTSI4_Output_SelectDA_START1 4
#define _kRTSI4_Output_SelectG_SRC_0 5
#define _kRTSI4_Output_SelectG_GATE_0 6
#define _kRTSI4_Output_SelectRGOUT0 7
#define _kRTSI4_Output_SelectRTSI_BRD_0 8
#define _kRTSI4_Output_SelectRTSI_BRD_1 9
#define _kRTSI4_Output_SelectRTSI_BRD_2 10
#define _kRTSI4_Output_SelectRTSI_BRD_3 11
#define _kRTSI4_Output_SelectRTSI_OSC 12
#define _kRTSI5_Output_SelectADR_START1 0
#define _kRTSI5_Output_SelectADR_START2 1
#define _kRTSI5_Output_SelectSCLKG 2
#define _kRTSI5_Output_SelectDACUPDN 3
#define _kRTSI5_Output_SelectDA_START1 4
#define _kRTSI5_Output_SelectG_SRC_0 5
#define _kRTSI5_Output_SelectG_GATE_0 6
#define _kRTSI5_Output_SelectRGOUT0 7
#define _kRTSI5_Output_SelectRTSI_BRD_0 8
#define _kRTSI5_Output_SelectRTSI_BRD_1 9
#define _kRTSI5_Output_SelectRTSI_BRD_2 10
#define _kRTSI5_Output_SelectRTSI_BRD_3 11
#define _kRTSI5_Output_SelectRTSI_OSC 12
#define _kRTSI6_Output_SelectADR_START1 0
#define _kRTSI6_Output_SelectADR_START2 1
#define _kRTSI6_Output_SelectSCLKG 2
#define _kRTSI6_Output_SelectDACUPDN 3
#define _kRTSI6_Output_SelectDA_START1 4
#define _kRTSI6_Output_SelectG_SRC_0 5
#define _kRTSI6_Output_SelectG_GATE_0 6
#define _kRTSI6_Output_SelectRGOUT0 7
#define _kRTSI6_Output_SelectRTSI_BRD_0 8
#define _kRTSI6_Output_SelectRTSI_BRD_1 9
#define _kRTSI6_Output_SelectRTSI_BRD_2 10
#define _kRTSI6_Output_SelectRTSI_BRD_3 11
#define _kRTSI6_Output_SelectRTSI_OSC 12
#define _kRTSI7_Output_SelectADR_START1 0
#define _kRTSI7_Output_SelectADR_START2 1
#define _kRTSI7_Output_SelectSCLKG 2
#define _kRTSI7_Output_SelectDACUPDN 3
#define _kRTSI7_Output_SelectDA_START1 4
#define _kRTSI7_Output_SelectG_SRC_0 5
#define _kRTSI7_Output_SelectG_GATE_0 6
#define _kRTSI7_Output_SelectRGOUT0 7
#define _kRTSI7_Output_SelectRTSI_BRD_0 8
#define _kRTSI7_Output_SelectRTSI_BRD_1 9
#define _kRTSI7_Output_SelectRTSI_BRD_2 10
#define _kRTSI7_Output_SelectRTSI_BRD_3 11
#define _kRTSI7_Output_SelectRTSI_OSC 12
         
#define _kG0_DMA_Enable 1
#define _kG0_DMA_Write 2
#define _kG0_DMA_Int_Enable 3
#define _kG0_DMA_Reset 4
#define _kG0_DMA_BankSW_Error 5
         
#define _kG1_DMA_Enable 1
#define _kG1_DMA_Write 2
#define _kG1_DMA_Int_Enable 3
#define _kG1_DMA_Reset 4
#define _kG1_DMA_BankSW_Error 5
         
#define _kG0_Pstat 1
#define _kG0_DMA_Readbank 7
#define _kG0_DRQ_Error_St 8
#define _kG0_DRQ_St 9
         
#define _kG1_Pstat 1
#define _kG1_DMA_Readbank 7
#define _kG1_DRQ_Error_St 8
#define _kG1_DRQ_St 9
         
#define _kCDI_DMA_Select 1
#define _kCDO_DMA_Select 2
         
#define _kSCXI_SW_SPIClk 1
#define _kSCXI_Back_Plane_MISO_Enable 2
#define _kSCXI_Front_Panel_MISO_Enable 3
#define _kSCXI_Intr 4
#define _kSCXI_D_A 5
#define _kSCXI_HW_Serial_Timebase 6
#define _kSCXI_HW_Serial_Start 7
#define _kSCXI_HW_Serial_Enable 8
#define _kSCXI_HW_Serial_Timebase100kHz 0
#define _kSCXI_HW_Serial_Timebase1MHz 1
         
#define _kAI_Trigger_Once 1
#define _kAI_Continuous 2
#define _kAI_Start_Stop 4
#define _kAI_SI_Source_Polarity 5
#define _kAI_CONVERT_Source_Polarity 6
#define _kAI_SI_Source_Select 7
#define _kAI_CONVERT_Source_Select 8
#define _kAI_SI_Source_PolarityRising_Edge 0
#define _kAI_SI_Source_PolarityFalling_Edge 1
#define _kAI_CONVERT_Source_PolarityFalling_Edge 0
#define _kAI_CONVERT_Source_PolarityRising_Edge 1
#define _kAI_SI_Source_SelectGround 0
#define _kAI_SI_Source_SelectPFI0 1
#define _kAI_SI_Source_SelectPFI1 2
#define _kAI_SI_Source_SelectPFI2 3
#define _kAI_SI_Source_SelectPFI3 4
#define _kAI_SI_Source_SelectPFI4 5
#define _kAI_SI_Source_SelectPFI5 6
#define _kAI_SI_Source_SelectPFI6 7
#define _kAI_SI_Source_SelectPFI7 8
#define _kAI_SI_Source_SelectPFI8 9
#define _kAI_SI_Source_SelectPFI9 10
#define _kAI_SI_Source_SelectRTSI0 11
#define _kAI_SI_Source_SelectRTSI1 12
#define _kAI_SI_Source_SelectRTSI2 13
#define _kAI_SI_Source_SelectRTSI3 14
#define _kAI_SI_Source_SelectRTSI4 15
#define _kAI_SI_Source_SelectRTSI5 16
#define _kAI_SI_Source_SelectRTSI6 17
#define _kAI_SI_Source_SelectINTIMEBASE2 19
#define _kAI_SI_Source_SelectStar_Trigger 20
#define _kAI_SI_Source_SelectPFI10 21
#define _kAI_SI_Source_SelectPFI11 22
#define _kAI_SI_Source_SelectPFI12 23
#define _kAI_SI_Source_SelectPFI13 24
#define _kAI_SI_Source_SelectPFI14 25
#define _kAI_SI_Source_SelectPFI15 26
#define _kAI_SI_Source_SelectRTSI7 27
#define _kAI_SI_Source_SelectINTIMEBASE1 28
#define _kAI_SI_Source_SelectPXI_Clk10 29
#define _kAI_SI_Source_SelectAnalog_Trigger 30
#define _kAI_SI_Source_SelectLow 31
#define _kAI_CONVERT_Source_SelectSI2TC 0
#define _kAI_CONVERT_Source_SelectPFI0 1
#define _kAI_CONVERT_Source_SelectPFI1 2
#define _kAI_CONVERT_Source_SelectPFI2 3
#define _kAI_CONVERT_Source_SelectPFI3 4
#define _kAI_CONVERT_Source_SelectPFI4 5
#define _kAI_CONVERT_Source_SelectPFI5 6
#define _kAI_CONVERT_Source_SelectPFI6 7
#define _kAI_CONVERT_Source_SelectPFI7 8
#define _kAI_CONVERT_Source_SelectPFI8 9
#define _kAI_CONVERT_Source_SelectPFI9 10
#define _kAI_CONVERT_Source_SelectRTSI0 11
#define _kAI_CONVERT_Source_SelectRTSI1 12
#define _kAI_CONVERT_Source_SelectRTSI2 13
#define _kAI_CONVERT_Source_SelectRTSI3 14
#define _kAI_CONVERT_Source_SelectRTSI4 15
#define _kAI_CONVERT_Source_SelectRTSI5 16
#define _kAI_CONVERT_Source_SelectRTSI6 17
#define _kAI_CONVERT_Source_SelectGPCtr1_Out 18
#define _kAI_CONVERT_Source_SelectGPCtr0_Out 19
#define _kAI_CONVERT_Source_SelectStar_Trigger 20
#define _kAI_CONVERT_Source_SelectPFI10 21
#define _kAI_CONVERT_Source_SelectPFI11 22
#define _kAI_CONVERT_Source_SelectPFI12 23
#define _kAI_CONVERT_Source_SelectPFI13 24
#define _kAI_CONVERT_Source_SelectPFI14 25
#define _kAI_CONVERT_Source_SelectPFI15 26
#define _kAI_CONVERT_Source_SelectRTSI7 27
#define _kAI_CONVERT_Source_SelectAnalog_Trigger 30
#define _kAI_CONVERT_Source_SelectLow 31
         
#define _kSCXI_Shift_In_Prog 1
         
#define _kSCXI_Dedicated_Output_Enable 1
#define _kSCXI_Trig1_Output_Enable 2
#define _kSCXI_Trig0_Output_Enable 3
#define _kSCXI_Trig1_Output_Select 4
#define _kSCXI_Dedicated_Output_EnableInput 0
#define _kSCXI_Dedicated_Output_EnableOutput 1
#define _kSCXI_Trig1_Output_EnableInput 0
#define _kSCXI_Trig1_Output_EnableOutput 1
#define _kSCXI_Trig0_Output_EnableInput 0
#define _kSCXI_Trig0_Output_EnableOutput 1
#define _kSCXI_Trig1_Output_SelectPFI0 0
#define _kSCXI_Trig1_Output_SelectPFI1 1
#define _kSCXI_Trig1_Output_SelectPFI2 2
#define _kSCXI_Trig1_Output_SelectPFI3 3
#define _kSCXI_Trig1_Output_SelectPFI4 4
#define _kSCXI_Trig1_Output_SelectPFI5 5
#define _kSCXI_Trig1_Output_SelectPFI6 6
#define _kSCXI_Trig1_Output_SelectPFI7 7
#define _kSCXI_Trig1_Output_SelectPFI8 8
#define _kSCXI_Trig1_Output_SelectPFI9 9
#define _kSCXI_Trig1_Output_SelectPFI10 10
#define _kSCXI_Trig1_Output_SelectPFI11 11
#define _kSCXI_Trig1_Output_SelectPFI12 12
#define _kSCXI_Trig1_Output_SelectPFI13 13
#define _kSCXI_Trig1_Output_SelectPFI14 14
#define _kSCXI_Trig1_Output_SelectPFI15 15
#define _kSCXI_Trig1_Output_SelectRTSI0 16
#define _kSCXI_Trig1_Output_SelectRTSI1 17
#define _kSCXI_Trig1_Output_SelectRTSI2 18
#define _kSCXI_Trig1_Output_SelectRTSI3 19
#define _kSCXI_Trig1_Output_SelectRTSI4 20
#define _kSCXI_Trig1_Output_SelectRTSI5 21
#define _kSCXI_Trig1_Output_SelectRTSI6 22
#define _kSCXI_Trig1_Output_SelectRTSI7 23
#define _kSCXI_Trig1_Output_SelectAI_Start 24
#define _kSCXI_Trig1_Output_SelectLow 31
         
#define _kSCXI_DIO_MOSI_Enable 1
#define _kSCXI_DIO_D_A_Enable 2
#define _kSCXI_DIO_Intr_Enable 3
#define _kSCXI_DIO_MOSI_EnableInput 0
#define _kSCXI_DIO_MOSI_EnableOutput 1
#define _kSCXI_DIO_D_A_EnableInput 0
#define _kSCXI_DIO_D_A_EnableOutput 1
#define _kSCXI_DIO_Intr_EnableInput 0
#define _kSCXI_DIO_Intr_EnableOutput 1
         
#define _kAO_MUDS_0_Interrupt_Enable 1
#define _kAO_MUDS_1_Interrupt_Enable 2
#define _kAO_MUDS_2_Interrupt_Enable 3
#define _kAO_MUDS_3_Interrupt_Enable 4
         
#define _kAO_MUDS_0_Interrupt_Ack 1
#define _kAO_MUDS_1_Interrupt_Ack 2
#define _kAO_MUDS_2_Interrupt_Ack 3
#define _kAO_MUDS_3_Interrupt_Ack 4
         
#define _kAO_MUDS_0_Interrupt_St 1
#define _kAO_MUDS_1_Interrupt_St 2
#define _kAO_MUDS_2_Interrupt_St 3
#define _kAO_MUDS_3_Interrupt_St 4
         
#define _kInterrupt_Group_C_Enable 1
         
#define _kInterrupt_Group_C_Status 1
         
#define _kAnalog_Trigger_Select 1
#define _kAnalog_Trigger_SelectAI_Chan 0
#define _kAnalog_Trigger_SelectAPFI0 1
#define _kAnalog_Trigger_SelectAPFI1 2
#define _kAnalog_Trigger_SelectGround 3
         
#define _kAI_DMA_Select 1
#define _kAO_DMA_Select 2
         
#define _kAI_Config_Channel 1
#define _kAI_Config_Bank 2
#define _kAI_Config_Channel_Type 3
#define _kAI_Config_Gain 4
#define _kAI_Config_Polarity 5
#define _kAI_Config_Dither 6
#define _kAI_Config_Last_Channel 7
#define _kAI_Config_Channel_TypeCalibration 0
#define _kAI_Config_Channel_TypeDifferential 1
#define _kAI_Config_Channel_TypeNRSE 2
#define _kAI_Config_Channel_TypeRSE 3
#define _kAI_Config_Channel_TypeAux 5
#define _kAI_Config_Channel_TypeGhost 7
#define _kAI_Config_PolarityBipolar 0
#define _kAI_Config_PolarityUnipolar 1
         
#define _kG0_DMA_Select 1
#define _kG1_DMA_Select 2
         
#define _kIntExtTrig 2
#define _kIntExtTrigTRIG1 0
#define _kIntExtTrigPGIA2 1
         
#define _kAO_RefGround 1
         
#define _kPFI0_Output_Select 1
#define _kPFI1_Output_Select 2
#define _kPFI2_Output_Select 3
#define _kPFI0_Output_SelectPFI_Default_Out 0
#define _kPFI0_Output_SelectAI_Start1_PFI 1
#define _kPFI0_Output_SelectAI_Start2_PFI 2
#define _kPFI0_Output_SelectAI_Convert 3
#define _kPFI0_Output_SelectG1_Selected_SRC 4
#define _kPFI0_Output_SelectG1_Selected_GATE 5
#define _kPFI0_Output_SelectAO_UPDATE_N 6
#define _kPFI0_Output_SelectAO_Start1_PFI 7
#define _kPFI0_Output_SelectAI_Start_Pulse 8
#define _kPFI0_Output_SelectG0_Selected_SRC 9
#define _kPFI0_Output_SelectG0_Selected_GATE 10
#define _kPFI0_Output_SelectExtStrobe 11
#define _kPFI0_Output_SelectAI_ExternalMUX_Clk 12
#define _kPFI0_Output_SelectG0_Out 13
#define _kPFI0_Output_SelectG1_Out 14
#define _kPFI0_Output_SelectFreq_Out 15
#define _kPFI0_Output_SelectPFI_DO 16
#define _kPFI0_Output_SelectI_Atrig 17
#define _kPFI0_Output_SelectRTSI_Pin0 18
#define _kPFI0_Output_SelectRTSI_Pin1 19
#define _kPFI0_Output_SelectRTSI_Pin2 20
#define _kPFI0_Output_SelectRTSI_Pin3 21
#define _kPFI0_Output_SelectRTSI_Pin4 22
#define _kPFI0_Output_SelectRTSI_Pin5 23
#define _kPFI0_Output_SelectRTSI_Pin6 24
#define _kPFI0_Output_SelectRTSI_Pin7 25
#define _kPFI0_Output_SelectStar_Trig_In 26
#define _kPFI0_Output_SelectSCXI_Trig1 27
#define _kPFI0_Output_SelectDIO_ChangeDetect_RTSI 28
#define _kPFI0_Output_SelectCDI_Sample 29
#define _kPFI0_Output_SelectCDO_Update 30
#define _kPFI1_Output_SelectPFI_Default_Out 0
#define _kPFI1_Output_SelectAI_Start1_PFI 1
#define _kPFI1_Output_SelectAI_Start2_PFI 2
#define _kPFI1_Output_SelectAI_Convert 3
#define _kPFI1_Output_SelectG1_Selected_SRC 4
#define _kPFI1_Output_SelectG1_Selected_GATE 5
#define _kPFI1_Output_SelectAO_UPDATE_N 6
#define _kPFI1_Output_SelectAO_Start1_PFI 7
#define _kPFI1_Output_SelectAI_Start_Pulse 8
#define _kPFI1_Output_SelectG0_Selected_SRC 9
#define _kPFI1_Output_SelectG0_Selected_GATE 10
#define _kPFI1_Output_SelectExtStrobe 11
#define _kPFI1_Output_SelectAI_ExternalMUX_Clk 12
#define _kPFI1_Output_SelectG0_Out 13
#define _kPFI1_Output_SelectG1_Out 14
#define _kPFI1_Output_SelectFreq_Out 15
#define _kPFI1_Output_SelectPFI_DO 16
#define _kPFI1_Output_SelectI_Atrig 17
#define _kPFI1_Output_SelectRTSI_Pin0 18
#define _kPFI1_Output_SelectRTSI_Pin1 19
#define _kPFI1_Output_SelectRTSI_Pin2 20
#define _kPFI1_Output_SelectRTSI_Pin3 21
#define _kPFI1_Output_SelectRTSI_Pin4 22
#define _kPFI1_Output_SelectRTSI_Pin5 23
#define _kPFI1_Output_SelectRTSI_Pin6 24
#define _kPFI1_Output_SelectRTSI_Pin7 25
#define _kPFI1_Output_SelectStar_Trig_In 26
#define _kPFI1_Output_SelectSCXI_Trig1 27
#define _kPFI1_Output_SelectDIO_ChangeDetect_RTSI 28
#define _kPFI1_Output_SelectCDI_Sample 29
#define _kPFI1_Output_SelectCDO_Update 30
#define _kPFI2_Output_SelectPFI_Default_Out 0
#define _kPFI2_Output_SelectAI_Start1_PFI 1
#define _kPFI2_Output_SelectAI_Start2_PFI 2
#define _kPFI2_Output_SelectAI_Convert 3
#define _kPFI2_Output_SelectG1_Selected_SRC 4
#define _kPFI2_Output_SelectG1_Selected_GATE 5
#define _kPFI2_Output_SelectAO_UPDATE_N 6
#define _kPFI2_Output_SelectAO_Start1_PFI 7
#define _kPFI2_Output_SelectAI_Start_Pulse 8
#define _kPFI2_Output_SelectG0_Selected_SRC 9
#define _kPFI2_Output_SelectG0_Selected_GATE 10
#define _kPFI2_Output_SelectExtStrobe 11
#define _kPFI2_Output_SelectAI_ExternalMUX_Clk 12
#define _kPFI2_Output_SelectG0_Out 13
#define _kPFI2_Output_SelectG1_Out 14
#define _kPFI2_Output_SelectFreq_Out 15
#define _kPFI2_Output_SelectPFI_DO 16
#define _kPFI2_Output_SelectI_Atrig 17
#define _kPFI2_Output_SelectRTSI_Pin0 18
#define _kPFI2_Output_SelectRTSI_Pin1 19
#define _kPFI2_Output_SelectRTSI_Pin2 20
#define _kPFI2_Output_SelectRTSI_Pin3 21
#define _kPFI2_Output_SelectRTSI_Pin4 22
#define _kPFI2_Output_SelectRTSI_Pin5 23
#define _kPFI2_Output_SelectRTSI_Pin6 24
#define _kPFI2_Output_SelectRTSI_Pin7 25
#define _kPFI2_Output_SelectStar_Trig_In 26
#define _kPFI2_Output_SelectSCXI_Trig1 27
#define _kPFI2_Output_SelectDIO_ChangeDetect_RTSI 28
#define _kPFI2_Output_SelectCDI_Sample 29
#define _kPFI2_Output_SelectCDO_Update 30
         
#define _kPFI3_Output_Select 1
#define _kPFI4_Output_Select 2
#define _kPFI5_Output_Select 3
#define _kPFI3_Output_SelectPFI_Default_Out 0
#define _kPFI3_Output_SelectAI_Start1_PFI 1
#define _kPFI3_Output_SelectAI_Start2_PFI 2
#define _kPFI3_Output_SelectAI_Convert 3
#define _kPFI3_Output_SelectG1_Selected_SRC 4
#define _kPFI3_Output_SelectG1_Selected_GATE 5
#define _kPFI3_Output_SelectAO_UPDATE_N 6
#define _kPFI3_Output_SelectAO_Start1_PFI 7
#define _kPFI3_Output_SelectAI_Start_Pulse 8
#define _kPFI3_Output_SelectG0_Selected_SRC 9
#define _kPFI3_Output_SelectG0_Selected_GATE 10
#define _kPFI3_Output_SelectExtStrobe 11
#define _kPFI3_Output_SelectAI_ExternalMUX_Clk 12
#define _kPFI3_Output_SelectG0_Out 13
#define _kPFI3_Output_SelectG1_Out 14
#define _kPFI3_Output_SelectFreq_Out 15
#define _kPFI3_Output_SelectPFI_DO 16
#define _kPFI3_Output_SelectI_Atrig 17
#define _kPFI3_Output_SelectRTSI_Pin0 18
#define _kPFI3_Output_SelectRTSI_Pin1 19
#define _kPFI3_Output_SelectRTSI_Pin2 20
#define _kPFI3_Output_SelectRTSI_Pin3 21
#define _kPFI3_Output_SelectRTSI_Pin4 22
#define _kPFI3_Output_SelectRTSI_Pin5 23
#define _kPFI3_Output_SelectRTSI_Pin6 24
#define _kPFI3_Output_SelectRTSI_Pin7 25
#define _kPFI3_Output_SelectStar_Trig_In 26
#define _kPFI3_Output_SelectSCXI_Trig1 27
#define _kPFI3_Output_SelectDIO_ChangeDetect_RTSI 28
#define _kPFI3_Output_SelectCDI_Sample 29
#define _kPFI3_Output_SelectCDO_Update 30
#define _kPFI4_Output_SelectPFI_Default_Out 0
#define _kPFI4_Output_SelectAI_Start1_PFI 1
#define _kPFI4_Output_SelectAI_Start2_PFI 2
#define _kPFI4_Output_SelectAI_Convert 3
#define _kPFI4_Output_SelectG1_Selected_SRC 4
#define _kPFI4_Output_SelectG1_Selected_GATE 5
#define _kPFI4_Output_SelectAO_UPDATE_N 6
#define _kPFI4_Output_SelectAO_Start1_PFI 7
#define _kPFI4_Output_SelectAI_Start_Pulse 8
#define _kPFI4_Output_SelectG0_Selected_SRC 9
#define _kPFI4_Output_SelectG0_Selected_GATE 10
#define _kPFI4_Output_SelectExtStrobe 11
#define _kPFI4_Output_SelectAI_ExternalMUX_Clk 12
#define _kPFI4_Output_SelectG0_Out 13
#define _kPFI4_Output_SelectG1_Out 14
#define _kPFI4_Output_SelectFreq_Out 15
#define _kPFI4_Output_SelectPFI_DO 16
#define _kPFI4_Output_SelectI_Atrig 17
#define _kPFI4_Output_SelectRTSI_Pin0 18
#define _kPFI4_Output_SelectRTSI_Pin1 19
#define _kPFI4_Output_SelectRTSI_Pin2 20
#define _kPFI4_Output_SelectRTSI_Pin3 21
#define _kPFI4_Output_SelectRTSI_Pin4 22
#define _kPFI4_Output_SelectRTSI_Pin5 23
#define _kPFI4_Output_SelectRTSI_Pin6 24
#define _kPFI4_Output_SelectRTSI_Pin7 25
#define _kPFI4_Output_SelectStar_Trig_In 26
#define _kPFI4_Output_SelectSCXI_Trig1 27
#define _kPFI4_Output_SelectDIO_ChangeDetect_RTSI 28
#define _kPFI4_Output_SelectCDI_Sample 29
#define _kPFI4_Output_SelectCDO_Update 30
#define _kPFI5_Output_SelectPFI_Default_Out 0
#define _kPFI5_Output_SelectAI_Start1_PFI 1
#define _kPFI5_Output_SelectAI_Start2_PFI 2
#define _kPFI5_Output_SelectAI_Convert 3
#define _kPFI5_Output_SelectG1_Selected_SRC 4
#define _kPFI5_Output_SelectG1_Selected_GATE 5
#define _kPFI5_Output_SelectAO_UPDATE_N 6
#define _kPFI5_Output_SelectAO_Start1_PFI 7
#define _kPFI5_Output_SelectAI_Start_Pulse 8
#define _kPFI5_Output_SelectG0_Selected_SRC 9
#define _kPFI5_Output_SelectG0_Selected_GATE 10
#define _kPFI5_Output_SelectExtStrobe 11
#define _kPFI5_Output_SelectAI_ExternalMUX_Clk 12
#define _kPFI5_Output_SelectG0_Out 13
#define _kPFI5_Output_SelectG1_Out 14
#define _kPFI5_Output_SelectFreq_Out 15
#define _kPFI5_Output_SelectPFI_DO 16
#define _kPFI5_Output_SelectI_Atrig 17
#define _kPFI5_Output_SelectRTSI_Pin0 18
#define _kPFI5_Output_SelectRTSI_Pin1 19
#define _kPFI5_Output_SelectRTSI_Pin2 20
#define _kPFI5_Output_SelectRTSI_Pin3 21
#define _kPFI5_Output_SelectRTSI_Pin4 22
#define _kPFI5_Output_SelectRTSI_Pin5 23
#define _kPFI5_Output_SelectRTSI_Pin6 24
#define _kPFI5_Output_SelectRTSI_Pin7 25
#define _kPFI5_Output_SelectStar_Trig_In 26
#define _kPFI5_Output_SelectSCXI_Trig1 27
#define _kPFI5_Output_SelectDIO_ChangeDetect_RTSI 28
#define _kPFI5_Output_SelectCDI_Sample 29
#define _kPFI5_Output_SelectCDO_Update 30
         
#define _kPFI6_Output_Select 1
#define _kPFI7_Output_Select 2
#define _kPFI8_Output_Select 3
#define _kPFI6_Output_SelectPFI_Default_Out 0
#define _kPFI6_Output_SelectAI_Start1_PFI 1
#define _kPFI6_Output_SelectAI_Start2_PFI 2
#define _kPFI6_Output_SelectAI_Convert 3
#define _kPFI6_Output_SelectG1_Selected_SRC 4
#define _kPFI6_Output_SelectG1_Selected_GATE 5
#define _kPFI6_Output_SelectAO_UPDATE_N 6
#define _kPFI6_Output_SelectAO_Start1_PFI 7
#define _kPFI6_Output_SelectAI_Start_Pulse 8
#define _kPFI6_Output_SelectG0_Selected_SRC 9
#define _kPFI6_Output_SelectG0_Selected_GATE 10
#define _kPFI6_Output_SelectExtStrobe 11
#define _kPFI6_Output_SelectAI_ExternalMUX_Clk 12
#define _kPFI6_Output_SelectG0_Out 13
#define _kPFI6_Output_SelectG1_Out 14
#define _kPFI6_Output_SelectFreq_Out 15
#define _kPFI6_Output_SelectPFI_DO 16
#define _kPFI6_Output_SelectI_Atrig 17
#define _kPFI6_Output_SelectRTSI_Pin0 18
#define _kPFI6_Output_SelectRTSI_Pin1 19
#define _kPFI6_Output_SelectRTSI_Pin2 20
#define _kPFI6_Output_SelectRTSI_Pin3 21
#define _kPFI6_Output_SelectRTSI_Pin4 22
#define _kPFI6_Output_SelectRTSI_Pin5 23
#define _kPFI6_Output_SelectRTSI_Pin6 24
#define _kPFI6_Output_SelectRTSI_Pin7 25
#define _kPFI6_Output_SelectStar_Trig_In 26
#define _kPFI6_Output_SelectSCXI_Trig1 27
#define _kPFI6_Output_SelectDIO_ChangeDetect_RTSI 28
#define _kPFI6_Output_SelectCDI_Sample 29
#define _kPFI6_Output_SelectCDO_Update 30
#define _kPFI7_Output_SelectPFI_Default_Out 0
#define _kPFI7_Output_SelectAI_Start1_PFI 1
#define _kPFI7_Output_SelectAI_Start2_PFI 2
#define _kPFI7_Output_SelectAI_Convert 3
#define _kPFI7_Output_SelectG1_Selected_SRC 4
#define _kPFI7_Output_SelectG1_Selected_GATE 5
#define _kPFI7_Output_SelectAO_UPDATE_N 6
#define _kPFI7_Output_SelectAO_Start1_PFI 7
#define _kPFI7_Output_SelectAI_Start_Pulse 8
#define _kPFI7_Output_SelectG0_Selected_SRC 9
#define _kPFI7_Output_SelectG0_Selected_GATE 10
#define _kPFI7_Output_SelectExtStrobe 11
#define _kPFI7_Output_SelectAI_ExternalMUX_Clk 12
#define _kPFI7_Output_SelectG0_Out 13
#define _kPFI7_Output_SelectG1_Out 14
#define _kPFI7_Output_SelectFreq_Out 15
#define _kPFI7_Output_SelectPFI_DO 16
#define _kPFI7_Output_SelectI_Atrig 17
#define _kPFI7_Output_SelectRTSI_Pin0 18
#define _kPFI7_Output_SelectRTSI_Pin1 19
#define _kPFI7_Output_SelectRTSI_Pin2 20
#define _kPFI7_Output_SelectRTSI_Pin3 21
#define _kPFI7_Output_SelectRTSI_Pin4 22
#define _kPFI7_Output_SelectRTSI_Pin5 23
#define _kPFI7_Output_SelectRTSI_Pin6 24
#define _kPFI7_Output_SelectRTSI_Pin7 25
#define _kPFI7_Output_SelectStar_Trig_In 26
#define _kPFI7_Output_SelectSCXI_Trig1 27
#define _kPFI7_Output_SelectDIO_ChangeDetect_RTSI 28
#define _kPFI7_Output_SelectCDI_Sample 29
#define _kPFI7_Output_SelectCDO_Update 30
#define _kPFI8_Output_SelectPFI_Default_Out 0
#define _kPFI8_Output_SelectAI_Start1_PFI 1
#define _kPFI8_Output_SelectAI_Start2_PFI 2
#define _kPFI8_Output_SelectAI_Convert 3
#define _kPFI8_Output_SelectG1_Selected_SRC 4
#define _kPFI8_Output_SelectG1_Selected_GATE 5
#define _kPFI8_Output_SelectAO_UPDATE_N 6
#define _kPFI8_Output_SelectAO_Start1_PFI 7
#define _kPFI8_Output_SelectAI_Start_Pulse 8
#define _kPFI8_Output_SelectG0_Selected_SRC 9
#define _kPFI8_Output_SelectG0_Selected_GATE 10
#define _kPFI8_Output_SelectExtStrobe 11
#define _kPFI8_Output_SelectAI_ExternalMUX_Clk 12
#define _kPFI8_Output_SelectG0_Out 13
#define _kPFI8_Output_SelectG1_Out 14
#define _kPFI8_Output_SelectFreq_Out 15
#define _kPFI8_Output_SelectPFI_DO 16
#define _kPFI8_Output_SelectI_Atrig 17
#define _kPFI8_Output_SelectRTSI_Pin0 18
#define _kPFI8_Output_SelectRTSI_Pin1 19
#define _kPFI8_Output_SelectRTSI_Pin2 20
#define _kPFI8_Output_SelectRTSI_Pin3 21
#define _kPFI8_Output_SelectRTSI_Pin4 22
#define _kPFI8_Output_SelectRTSI_Pin5 23
#define _kPFI8_Output_SelectRTSI_Pin6 24
#define _kPFI8_Output_SelectRTSI_Pin7 25
#define _kPFI8_Output_SelectStar_Trig_In 26
#define _kPFI8_Output_SelectSCXI_Trig1 27
#define _kPFI8_Output_SelectDIO_ChangeDetect_RTSI 28
#define _kPFI8_Output_SelectCDI_Sample 29
#define _kPFI8_Output_SelectCDO_Update 30
         
#define _kPFI9_Output_Select 1
#define _kPFI10_Output_Select 2
#define _kPFI11_Output_Select 3
#define _kPFI9_Output_SelectPFI_Default_Out 0
#define _kPFI9_Output_SelectAI_Start1_PFI 1
#define _kPFI9_Output_SelectAI_Start2_PFI 2
#define _kPFI9_Output_SelectAI_Convert 3
#define _kPFI9_Output_SelectG1_Selected_SRC 4
#define _kPFI9_Output_SelectG1_Selected_GATE 5
#define _kPFI9_Output_SelectAO_UPDATE_N 6
#define _kPFI9_Output_SelectAO_Start1_PFI 7
#define _kPFI9_Output_SelectAI_Start_Pulse 8
#define _kPFI9_Output_SelectG0_Selected_SRC 9
#define _kPFI9_Output_SelectG0_Selected_GATE 10
#define _kPFI9_Output_SelectExtStrobe 11
#define _kPFI9_Output_SelectAI_ExternalMUX_Clk 12
#define _kPFI9_Output_SelectG0_Out 13
#define _kPFI9_Output_SelectG1_Out 14
#define _kPFI9_Output_SelectFreq_Out 15
#define _kPFI9_Output_SelectPFI_DO 16
#define _kPFI9_Output_SelectI_Atrig 17
#define _kPFI9_Output_SelectRTSI_Pin0 18
#define _kPFI9_Output_SelectRTSI_Pin1 19
#define _kPFI9_Output_SelectRTSI_Pin2 20
#define _kPFI9_Output_SelectRTSI_Pin3 21
#define _kPFI9_Output_SelectRTSI_Pin4 22
#define _kPFI9_Output_SelectRTSI_Pin5 23
#define _kPFI9_Output_SelectRTSI_Pin6 24
#define _kPFI9_Output_SelectRTSI_Pin7 25
#define _kPFI9_Output_SelectStar_Trig_In 26
#define _kPFI9_Output_SelectSCXI_Trig1 27
#define _kPFI9_Output_SelectDIO_ChangeDetect_RTSI 28
#define _kPFI9_Output_SelectCDI_Sample 29
#define _kPFI9_Output_SelectCDO_Update 30
#define _kPFI10_Output_SelectPFI_Default_Out 0
#define _kPFI10_Output_SelectAI_Start1_PFI 1
#define _kPFI10_Output_SelectAI_Start2_PFI 2
#define _kPFI10_Output_SelectAI_Convert 3
#define _kPFI10_Output_SelectG1_Selected_SRC 4
#define _kPFI10_Output_SelectG1_Selected_GATE 5
#define _kPFI10_Output_SelectAO_UPDATE_N 6
#define _kPFI10_Output_SelectAO_Start1_PFI 7
#define _kPFI10_Output_SelectAI_Start_Pulse 8
#define _kPFI10_Output_SelectG0_Selected_SRC 9
#define _kPFI10_Output_SelectG0_Selected_GATE 10
#define _kPFI10_Output_SelectExtStrobe 11
#define _kPFI10_Output_SelectAI_ExternalMUX_Clk 12
#define _kPFI10_Output_SelectG0_Out 13
#define _kPFI10_Output_SelectG1_Out 14
#define _kPFI10_Output_SelectFreq_Out 15
#define _kPFI10_Output_SelectPFI_DO 16
#define _kPFI10_Output_SelectI_Atrig 17
#define _kPFI10_Output_SelectRTSI_Pin0 18
#define _kPFI10_Output_SelectRTSI_Pin1 19
#define _kPFI10_Output_SelectRTSI_Pin2 20
#define _kPFI10_Output_SelectRTSI_Pin3 21
#define _kPFI10_Output_SelectRTSI_Pin4 22
#define _kPFI10_Output_SelectRTSI_Pin5 23
#define _kPFI10_Output_SelectRTSI_Pin6 24
#define _kPFI10_Output_SelectRTSI_Pin7 25
#define _kPFI10_Output_SelectStar_Trig_In 26
#define _kPFI10_Output_SelectSCXI_Trig1 27
#define _kPFI10_Output_SelectDIO_ChangeDetect_RTSI 28
#define _kPFI10_Output_SelectCDI_Sample 29
#define _kPFI10_Output_SelectCDO_Update 30
#define _kPFI11_Output_SelectPFI_Default_Out 0
#define _kPFI11_Output_SelectAI_Start1_PFI 1
#define _kPFI11_Output_SelectAI_Start2_PFI 2
#define _kPFI11_Output_SelectAI_Convert 3
#define _kPFI11_Output_SelectG1_Selected_SRC 4
#define _kPFI11_Output_SelectG1_Selected_GATE 5
#define _kPFI11_Output_SelectAO_UPDATE_N 6
#define _kPFI11_Output_SelectAO_Start1_PFI 7
#define _kPFI11_Output_SelectAI_Start_Pulse 8
#define _kPFI11_Output_SelectG0_Selected_SRC 9
#define _kPFI11_Output_SelectG0_Selected_GATE 10
#define _kPFI11_Output_SelectExtStrobe 11
#define _kPFI11_Output_SelectAI_ExternalMUX_Clk 12
#define _kPFI11_Output_SelectG0_Out 13
#define _kPFI11_Output_SelectG1_Out 14
#define _kPFI11_Output_SelectFreq_Out 15
#define _kPFI11_Output_SelectPFI_DO 16
#define _kPFI11_Output_SelectI_Atrig 17
#define _kPFI11_Output_SelectRTSI_Pin0 18
#define _kPFI11_Output_SelectRTSI_Pin1 19
#define _kPFI11_Output_SelectRTSI_Pin2 20
#define _kPFI11_Output_SelectRTSI_Pin3 21
#define _kPFI11_Output_SelectRTSI_Pin4 22
#define _kPFI11_Output_SelectRTSI_Pin5 23
#define _kPFI11_Output_SelectRTSI_Pin6 24
#define _kPFI11_Output_SelectRTSI_Pin7 25
#define _kPFI11_Output_SelectStar_Trig_In 26
#define _kPFI11_Output_SelectSCXI_Trig1 27
#define _kPFI11_Output_SelectDIO_ChangeDetect_RTSI 28
#define _kPFI11_Output_SelectCDI_Sample 29
#define _kPFI11_Output_SelectCDO_Update 30
         
#define _kPFI12_Output_Select 1
#define _kPFI13_Output_Select 2
#define _kPFI14_Output_Select 3
#define _kPFI12_Output_SelectPFI_Default_Out 0
#define _kPFI12_Output_SelectAI_Start1_PFI 1
#define _kPFI12_Output_SelectAI_Start2_PFI 2
#define _kPFI12_Output_SelectAI_Convert 3
#define _kPFI12_Output_SelectG1_Selected_SRC 4
#define _kPFI12_Output_SelectG1_Selected_GATE 5
#define _kPFI12_Output_SelectAO_UPDATE_N 6
#define _kPFI12_Output_SelectAO_Start1_PFI 7
#define _kPFI12_Output_SelectAI_Start_Pulse 8
#define _kPFI12_Output_SelectG0_Selected_SRC 9
#define _kPFI12_Output_SelectG0_Selected_GATE 10
#define _kPFI12_Output_SelectExtStrobe 11
#define _kPFI12_Output_SelectAI_ExternalMUX_Clk 12
#define _kPFI12_Output_SelectG0_Out 13
#define _kPFI12_Output_SelectG1_Out 14
#define _kPFI12_Output_SelectFreq_Out 15
#define _kPFI12_Output_SelectPFI_DO 16
#define _kPFI12_Output_SelectI_Atrig 17
#define _kPFI12_Output_SelectRTSI_Pin0 18
#define _kPFI12_Output_SelectRTSI_Pin1 19
#define _kPFI12_Output_SelectRTSI_Pin2 20
#define _kPFI12_Output_SelectRTSI_Pin3 21
#define _kPFI12_Output_SelectRTSI_Pin4 22
#define _kPFI12_Output_SelectRTSI_Pin5 23
#define _kPFI12_Output_SelectRTSI_Pin6 24
#define _kPFI12_Output_SelectRTSI_Pin7 25
#define _kPFI12_Output_SelectStar_Trig_In 26
#define _kPFI12_Output_SelectSCXI_Trig1 27
#define _kPFI12_Output_SelectDIO_ChangeDetect_RTSI 28
#define _kPFI12_Output_SelectCDI_Sample 29
#define _kPFI12_Output_SelectCDO_Update 30
#define _kPFI13_Output_SelectPFI_Default_Out 0
#define _kPFI13_Output_SelectAI_Start1_PFI 1
#define _kPFI13_Output_SelectAI_Start2_PFI 2
#define _kPFI13_Output_SelectAI_Convert 3
#define _kPFI13_Output_SelectG1_Selected_SRC 4
#define _kPFI13_Output_SelectG1_Selected_GATE 5
#define _kPFI13_Output_SelectAO_UPDATE_N 6
#define _kPFI13_Output_SelectAO_Start1_PFI 7
#define _kPFI13_Output_SelectAI_Start_Pulse 8
#define _kPFI13_Output_SelectG0_Selected_SRC 9
#define _kPFI13_Output_SelectG0_Selected_GATE 10
#define _kPFI13_Output_SelectExtStrobe 11
#define _kPFI13_Output_SelectAI_ExternalMUX_Clk 12
#define _kPFI13_Output_SelectG0_Out 13
#define _kPFI13_Output_SelectG1_Out 14
#define _kPFI13_Output_SelectFreq_Out 15
#define _kPFI13_Output_SelectPFI_DO 16
#define _kPFI13_Output_SelectI_Atrig 17
#define _kPFI13_Output_SelectRTSI_Pin0 18
#define _kPFI13_Output_SelectRTSI_Pin1 19
#define _kPFI13_Output_SelectRTSI_Pin2 20
#define _kPFI13_Output_SelectRTSI_Pin3 21
#define _kPFI13_Output_SelectRTSI_Pin4 22
#define _kPFI13_Output_SelectRTSI_Pin5 23
#define _kPFI13_Output_SelectRTSI_Pin6 24
#define _kPFI13_Output_SelectRTSI_Pin7 25
#define _kPFI13_Output_SelectStar_Trig_In 26
#define _kPFI13_Output_SelectSCXI_Trig1 27
#define _kPFI13_Output_SelectDIO_ChangeDetect_RTSI 28
#define _kPFI13_Output_SelectCDI_Sample 29
#define _kPFI13_Output_SelectCDO_Update 30
#define _kPFI14_Output_SelectPFI_Default_Out 0
#define _kPFI14_Output_SelectAI_Start1_PFI 1
#define _kPFI14_Output_SelectAI_Start2_PFI 2
#define _kPFI14_Output_SelectAI_Convert 3
#define _kPFI14_Output_SelectG1_Selected_SRC 4
#define _kPFI14_Output_SelectG1_Selected_GATE 5
#define _kPFI14_Output_SelectAO_UPDATE_N 6
#define _kPFI14_Output_SelectAO_Start1_PFI 7
#define _kPFI14_Output_SelectAI_Start_Pulse 8
#define _kPFI14_Output_SelectG0_Selected_SRC 9
#define _kPFI14_Output_SelectG0_Selected_GATE 10
#define _kPFI14_Output_SelectExtStrobe 11
#define _kPFI14_Output_SelectAI_ExternalMUX_Clk 12
#define _kPFI14_Output_SelectG0_Out 13
#define _kPFI14_Output_SelectG1_Out 14
#define _kPFI14_Output_SelectFreq_Out 15
#define _kPFI14_Output_SelectPFI_DO 16
#define _kPFI14_Output_SelectI_Atrig 17
#define _kPFI14_Output_SelectRTSI_Pin0 18
#define _kPFI14_Output_SelectRTSI_Pin1 19
#define _kPFI14_Output_SelectRTSI_Pin2 20
#define _kPFI14_Output_SelectRTSI_Pin3 21
#define _kPFI14_Output_SelectRTSI_Pin4 22
#define _kPFI14_Output_SelectRTSI_Pin5 23
#define _kPFI14_Output_SelectRTSI_Pin6 24
#define _kPFI14_Output_SelectRTSI_Pin7 25
#define _kPFI14_Output_SelectStar_Trig_In 26
#define _kPFI14_Output_SelectSCXI_Trig1 27
#define _kPFI14_Output_SelectDIO_ChangeDetect_RTSI 28
#define _kPFI14_Output_SelectCDI_Sample 29
#define _kPFI14_Output_SelectCDO_Update 30
         
#define _kPFI15_Output_Select 1
#define _kPFI15_Output_SelectPFI_Default_Out 0
#define _kPFI15_Output_SelectAI_Start1_PFI 1
#define _kPFI15_Output_SelectAI_Start2_PFI 2
#define _kPFI15_Output_SelectAI_Convert 3
#define _kPFI15_Output_SelectG1_Selected_SRC 4
#define _kPFI15_Output_SelectG1_Selected_GATE 5
#define _kPFI15_Output_SelectAO_UPDATE_N 6
#define _kPFI15_Output_SelectAO_Start1_PFI 7
#define _kPFI15_Output_SelectAI_Start_Pulse 8
#define _kPFI15_Output_SelectG0_Selected_SRC 9
#define _kPFI15_Output_SelectG0_Selected_GATE 10
#define _kPFI15_Output_SelectExtStrobe 11
#define _kPFI15_Output_SelectAI_ExternalMUX_Clk 12
#define _kPFI15_Output_SelectG0_Out 13
#define _kPFI15_Output_SelectG1_Out 14
#define _kPFI15_Output_SelectFreq_Out 15
#define _kPFI15_Output_SelectPFI_DO 16
#define _kPFI15_Output_SelectI_Atrig 17
#define _kPFI15_Output_SelectRTSI_Pin0 18
#define _kPFI15_Output_SelectRTSI_Pin1 19
#define _kPFI15_Output_SelectRTSI_Pin2 20
#define _kPFI15_Output_SelectRTSI_Pin3 21
#define _kPFI15_Output_SelectRTSI_Pin4 22
#define _kPFI15_Output_SelectRTSI_Pin5 23
#define _kPFI15_Output_SelectRTSI_Pin6 24
#define _kPFI15_Output_SelectRTSI_Pin7 25
#define _kPFI15_Output_SelectStar_Trig_In 26
#define _kPFI15_Output_SelectSCXI_Trig1 27
#define _kPFI15_Output_SelectDIO_ChangeDetect_RTSI 28
#define _kPFI15_Output_SelectCDI_Sample 29
#define _kPFI15_Output_SelectCDO_Update 30
         
#define _kLowerPort 1
#define _kUpperPort 2
         
#define _kPFI0_Filter_Select 1
#define _kPFI1_Filter_Select 2
#define _kPFI2_Filter_Select 3
#define _kPFI3_Filter_Select 4
#define _kPFI4_Filter_Select 5
#define _kPFI5_Filter_Select 6
#define _kPFI6_Filter_Select 7
#define _kPFI7_Filter_Select 8
#define _kPFI8_Filter_Select 9
#define _kPFI9_Filter_Select 10
#define _kPFI10_Filter_Select 11
#define _kPFI11_Filter_Select 12
#define _kPFI12_Filter_Select 13
#define _kPFI13_Filter_Select 14
#define _kPFI14_Filter_Select 15
#define _kPFI15_Filter_Select 16
#define _kPFI0_Filter_SelectNoFilter 0
#define _kPFI0_Filter_SelectSmallFilter 1
#define _kPFI0_Filter_SelectMediumFilter 2
#define _kPFI0_Filter_SelectLargeFilter 3
#define _kPFI0_Filter_SelectIllegalFilterSetting 4
#define _kPFI1_Filter_SelectNoFilter 0
#define _kPFI1_Filter_SelectSmallFilter 1
#define _kPFI1_Filter_SelectMediumFilter 2
#define _kPFI1_Filter_SelectLargeFilter 3
#define _kPFI1_Filter_SelectIllegalFilterSetting 4
#define _kPFI2_Filter_SelectNoFilter 0
#define _kPFI2_Filter_SelectSmallFilter 1
#define _kPFI2_Filter_SelectMediumFilter 2
#define _kPFI2_Filter_SelectLargeFilter 3
#define _kPFI2_Filter_SelectIllegalFilterSetting 4
#define _kPFI3_Filter_SelectNoFilter 0
#define _kPFI3_Filter_SelectSmallFilter 1
#define _kPFI3_Filter_SelectMediumFilter 2
#define _kPFI3_Filter_SelectLargeFilter 3
#define _kPFI3_Filter_SelectIllegalFilterSetting 4
#define _kPFI4_Filter_SelectNoFilter 0
#define _kPFI4_Filter_SelectSmallFilter 1
#define _kPFI4_Filter_SelectMediumFilter 2
#define _kPFI4_Filter_SelectLargeFilter 3
#define _kPFI4_Filter_SelectIllegalFilterSetting 4
#define _kPFI5_Filter_SelectNoFilter 0
#define _kPFI5_Filter_SelectSmallFilter 1
#define _kPFI5_Filter_SelectMediumFilter 2
#define _kPFI5_Filter_SelectLargeFilter 3
#define _kPFI5_Filter_SelectIllegalFilterSetting 4
#define _kPFI6_Filter_SelectNoFilter 0
#define _kPFI6_Filter_SelectSmallFilter 1
#define _kPFI6_Filter_SelectMediumFilter 2
#define _kPFI6_Filter_SelectLargeFilter 3
#define _kPFI6_Filter_SelectIllegalFilterSetting 4
#define _kPFI7_Filter_SelectNoFilter 0
#define _kPFI7_Filter_SelectSmallFilter 1
#define _kPFI7_Filter_SelectMediumFilter 2
#define _kPFI7_Filter_SelectLargeFilter 3
#define _kPFI7_Filter_SelectIllegalFilterSetting 4
#define _kPFI8_Filter_SelectNoFilter 0
#define _kPFI8_Filter_SelectSmallFilter 1
#define _kPFI8_Filter_SelectMediumFilter 2
#define _kPFI8_Filter_SelectLargeFilter 3
#define _kPFI8_Filter_SelectIllegalFilterSetting 4
#define _kPFI9_Filter_SelectNoFilter 0
#define _kPFI9_Filter_SelectSmallFilter 1
#define _kPFI9_Filter_SelectMediumFilter 2
#define _kPFI9_Filter_SelectLargeFilter 3
#define _kPFI9_Filter_SelectIllegalFilterSetting 4
#define _kPFI10_Filter_SelectNoFilter 0
#define _kPFI10_Filter_SelectSmallFilter 1
#define _kPFI10_Filter_SelectMediumFilter 2
#define _kPFI10_Filter_SelectLargeFilter 3
#define _kPFI10_Filter_SelectIllegalFilterSetting 4
#define _kPFI11_Filter_SelectNoFilter 0
#define _kPFI11_Filter_SelectSmallFilter 1
#define _kPFI11_Filter_SelectMediumFilter 2
#define _kPFI11_Filter_SelectLargeFilter 3
#define _kPFI11_Filter_SelectIllegalFilterSetting 4
#define _kPFI12_Filter_SelectNoFilter 0
#define _kPFI12_Filter_SelectSmallFilter 1
#define _kPFI12_Filter_SelectMediumFilter 2
#define _kPFI12_Filter_SelectLargeFilter 3
#define _kPFI12_Filter_SelectIllegalFilterSetting 4
#define _kPFI13_Filter_SelectNoFilter 0
#define _kPFI13_Filter_SelectSmallFilter 1
#define _kPFI13_Filter_SelectMediumFilter 2
#define _kPFI13_Filter_SelectLargeFilter 3
#define _kPFI13_Filter_SelectIllegalFilterSetting 4
#define _kPFI14_Filter_SelectNoFilter 0
#define _kPFI14_Filter_SelectSmallFilter 1
#define _kPFI14_Filter_SelectMediumFilter 2
#define _kPFI14_Filter_SelectLargeFilter 3
#define _kPFI14_Filter_SelectIllegalFilterSetting 4
#define _kPFI15_Filter_SelectNoFilter 0
#define _kPFI15_Filter_SelectSmallFilter 1
#define _kPFI15_Filter_SelectMediumFilter 2
#define _kPFI15_Filter_SelectLargeFilter 3
#define _kPFI15_Filter_SelectIllegalFilterSetting 4
         
#define _kRTSI0_Filter_Select 1
#define _kRTSI1_Filter_Select 2
#define _kRTSI2_Filter_Select 3
#define _kRTSI3_Filter_Select 4
#define _kRTSI4_Filter_Select 5
#define _kRTSI5_Filter_Select 6
#define _kRTSI6_Filter_Select 7
#define _kRTSI7_Filter_Select 8
#define _kRTSI0_Filter_SelectNoFilter 0
#define _kRTSI0_Filter_SelectSmallFilter 1
#define _kRTSI0_Filter_SelectMediumFilter 2
#define _kRTSI0_Filter_SelectLargeFilter 3
#define _kRTSI0_Filter_SelectIllegalFilterSetting 4
#define _kRTSI1_Filter_SelectNoFilter 0
#define _kRTSI1_Filter_SelectSmallFilter 1
#define _kRTSI1_Filter_SelectMediumFilter 2
#define _kRTSI1_Filter_SelectLargeFilter 3
#define _kRTSI1_Filter_SelectIllegalFilterSetting 4
#define _kRTSI2_Filter_SelectNoFilter 0
#define _kRTSI2_Filter_SelectSmallFilter 1
#define _kRTSI2_Filter_SelectMediumFilter 2
#define _kRTSI2_Filter_SelectLargeFilter 3
#define _kRTSI2_Filter_SelectIllegalFilterSetting 4
#define _kRTSI3_Filter_SelectNoFilter 0
#define _kRTSI3_Filter_SelectSmallFilter 1
#define _kRTSI3_Filter_SelectMediumFilter 2
#define _kRTSI3_Filter_SelectLargeFilter 3
#define _kRTSI3_Filter_SelectIllegalFilterSetting 4
#define _kRTSI4_Filter_SelectNoFilter 0
#define _kRTSI4_Filter_SelectSmallFilter 1
#define _kRTSI4_Filter_SelectMediumFilter 2
#define _kRTSI4_Filter_SelectLargeFilter 3
#define _kRTSI4_Filter_SelectIllegalFilterSetting 4
#define _kRTSI5_Filter_SelectNoFilter 0
#define _kRTSI5_Filter_SelectSmallFilter 1
#define _kRTSI5_Filter_SelectMediumFilter 2
#define _kRTSI5_Filter_SelectLargeFilter 3
#define _kRTSI5_Filter_SelectIllegalFilterSetting 4
#define _kRTSI6_Filter_SelectNoFilter 0
#define _kRTSI6_Filter_SelectSmallFilter 1
#define _kRTSI6_Filter_SelectMediumFilter 2
#define _kRTSI6_Filter_SelectLargeFilter 3
#define _kRTSI6_Filter_SelectIllegalFilterSetting 4
#define _kRTSI7_Filter_SelectNoFilter 0
#define _kRTSI7_Filter_SelectSmallFilter 1
#define _kRTSI7_Filter_SelectMediumFilter 2
#define _kRTSI7_Filter_SelectLargeFilter 3
#define _kRTSI7_Filter_SelectIllegalFilterSetting 4
         
#define _kPLL_In_Source_Select 1
#define _kTB1_Select 2
#define _kTB3_Select 3
#define _kRTSI_Clock_Freq 4
#define _kPLL_In_Source_SelectOld_RTSI7 0
#define _kPLL_In_Source_SelectRTSI0 11
#define _kPLL_In_Source_SelectRTSI1 12
#define _kPLL_In_Source_SelectRTSI2 13
#define _kPLL_In_Source_SelectRTSI3 14
#define _kPLL_In_Source_SelectRTSI4 15
#define _kPLL_In_Source_SelectRTSI5 16
#define _kPLL_In_Source_SelectRTSI6 17
#define _kPLL_In_Source_SelectStar_Trigger 20
#define _kPLL_In_Source_SelectRTSI7 27
#define _kPLL_In_Source_SelectPXI_Clock10 29
#define _kTB1_SelectSelect_OSC 0
#define _kTB1_SelectSelect_PLL 1
#define _kTB3_SelectSelect_OSC 0
#define _kTB3_SelectSelect_PLL 1
#define _kRTSI_Clock_Freq20MHz 0
#define _kRTSI_Clock_Freq10MHz 1
         
#define _kPLL_Multiplier 1
#define _kPLL_Divisor 2
#define _kPLL_Enable 3
#define _kPLL_VCO_Mode 4
#define _kPLL_VCO_ModeMode1_200_325MHz 0
#define _kPLL_VCO_ModeMode2_175_225MHz 1
#define _kPLL_VCO_ModeMode3_100_225MHz 2
#define _kPLL_VCO_ModeMode4_75_150MHz 3
         
#define _kPLL_Locked 1
         
#define _kAI_Bypass_Channel 1
#define _kAI_Bypass_Bank 2
#define _kAI_Bypass_Cal_Sel_Pos 3
#define _kAI_Bypass_Cal_Sel_Neg 4
#define _kAI_Bypass_Mode_Mux 5
#define _kAO_Bypass_AO_Cal_Sel 6
#define _kAI_Bypass_Gain 7
#define _kAI_Bypass_Dither 8
#define _kAI_Bypass_Polarity 9
#define _kAI_Bypass_Config_FIFO 18
         
#define _kCDO_FIFO_Empty_St 1
#define _kCDO_FIFO_Full_St 2
#define _kCDO_FIFO_Request_St 3
#define _kCDO_Overrun_St 4
#define _kCDO_Underflow_St 5
#define _kCDI_FIFO_Empty_St 17
#define _kCDI_FIFO_Full_St 18
#define _kCDI_FIFO_Request_St 19
#define _kCDI_Overrun_St 20
#define _kCDI_Overflow_St 21
         
#define _kCDO_Disarm 1
#define _kCDO_Arm 2
#define _kCDI_Disarm 3
#define _kCDI_Arm 4
#define _kCDO_Reset 5
#define _kCDI_Reset 6
#define _kCDO_Error_Interrupt_Enable_Set 7
#define _kCDO_Error_Interrupt_Enable_Clear 8
#define _kCDI_Error_Interrupt_Enable_Set 9
#define _kCDI_Error_Interrupt_Enable_Clear 10
#define _kCDO_FIFO_Request_Interrupt_Enable_Set 11
#define _kCDO_FIFO_Request_Interrupt_Enable_Clear 12
#define _kCDI_FIFO_Request_Interrupt_Enable_Set 13
#define _kCDI_FIFO_Request_Interrupt_Enable_Clear 14
#define _kCDO_Error_Interrupt_Confirm 15
#define _kCDI_Error_Interrupt_Confirm 16
#define _kCDO_Empty_FIFO_Interrupt_Enable_Set 17
#define _kCDO_Empty_FIFO_Interrupt_Enable_Clear 18
#define _kCDO_SW_Update 20
#define _kCDI_SW_Sample 21
         
#define _kCDI_Sample_Source_Select 1
#define _kCDI_Halt_On_Error 5
#define _kCDI_Polarity 6
#define _kCDI_FIFO_Mode 7
#define _kCDI_Data_Lane 8
#define _kCDI_Sample_Source_SelectGround 0
#define _kCDI_Sample_Source_SelectPFI0 1
#define _kCDI_Sample_Source_SelectPFI1 2
#define _kCDI_Sample_Source_SelectPFI2 3
#define _kCDI_Sample_Source_SelectPFI3 4
#define _kCDI_Sample_Source_SelectPFI4 5
#define _kCDI_Sample_Source_SelectPFI5 6
#define _kCDI_Sample_Source_SelectPFI6 7
#define _kCDI_Sample_Source_SelectPFI7 8
#define _kCDI_Sample_Source_SelectPFI8 9
#define _kCDI_Sample_Source_SelectPFI9 10
#define _kCDI_Sample_Source_SelectRTSI0 11
#define _kCDI_Sample_Source_SelectRTSI1 12
#define _kCDI_Sample_Source_SelectRTSI2 13
#define _kCDI_Sample_Source_SelectRTSI3 14
#define _kCDI_Sample_Source_SelectRTSI4 15
#define _kCDI_Sample_Source_SelectRTSI5 16
#define _kCDI_Sample_Source_SelectRTSI6 17
#define _kCDI_Sample_Source_SelectAI_Start 18
#define _kCDI_Sample_Source_SelectAI_Convert 19
#define _kCDI_Sample_Source_SelectPXI_Star_Trigger 20
#define _kCDI_Sample_Source_SelectPFI10 21
#define _kCDI_Sample_Source_SelectPFI11 22
#define _kCDI_Sample_Source_SelectPFI12 23
#define _kCDI_Sample_Source_SelectPFI13 24
#define _kCDI_Sample_Source_SelectPFI14 25
#define _kCDI_Sample_Source_SelectPFI15 26
#define _kCDI_Sample_Source_SelectRTSI7 27
#define _kCDI_Sample_Source_SelectG0_Out 28
#define _kCDI_Sample_Source_SelectG1_Out 29
#define _kCDI_Sample_Source_SelectAnalog_Trigger 30
#define _kCDI_Sample_Source_SelectAO_Update 31
#define _kCDI_Sample_Source_SelectFreq_Out 32
#define _kCDI_Sample_Source_SelectDIO_Change_Detect_Irq 33
#define _kCDI_PolarityRising 0
#define _kCDI_PolarityFalling 1
#define _kCDI_FIFO_ModeFIFO_Not_Empty 0
#define _kCDI_FIFO_ModeFIFO_Half_Full 1
#define _kCDI_Data_LaneCDIO_15_0 0
#define _kCDI_Data_LaneCDIO_31_16 1
#define _kCDI_Data_LaneCDIO_7_0 0
#define _kCDI_Data_LaneCDIO_15_8 1
#define _kCDI_Data_LaneCDIO_23_16 2
#define _kCDI_Data_LaneCDIO_31_24 3
         
#define _kCDO_Update_Source_Select 1
#define _kCDO_Retransmit 4
#define _kCDO_Halt_On_Error 5
#define _kCDO_Polarity 6
#define _kCDO_FIFO_Mode 7
#define _kCDO_Data_Lane 8
#define _kCDO_Update_Source_SelectGround 0
#define _kCDO_Update_Source_SelectPFI0 1
#define _kCDO_Update_Source_SelectPFI1 2
#define _kCDO_Update_Source_SelectPFI2 3
#define _kCDO_Update_Source_SelectPFI3 4
#define _kCDO_Update_Source_SelectPFI4 5
#define _kCDO_Update_Source_SelectPFI5 6
#define _kCDO_Update_Source_SelectPFI6 7
#define _kCDO_Update_Source_SelectPFI7 8
#define _kCDO_Update_Source_SelectPFI8 9
#define _kCDO_Update_Source_SelectPFI9 10
#define _kCDO_Update_Source_SelectRTSI0 11
#define _kCDO_Update_Source_SelectRTSI1 12
#define _kCDO_Update_Source_SelectRTSI2 13
#define _kCDO_Update_Source_SelectRTSI3 14
#define _kCDO_Update_Source_SelectRTSI4 15
#define _kCDO_Update_Source_SelectRTSI5 16
#define _kCDO_Update_Source_SelectRTSI6 17
#define _kCDO_Update_Source_SelectAI_Start 18
#define _kCDO_Update_Source_SelectAI_Convert 19
#define _kCDO_Update_Source_SelectPXI_Star_Trigger 20
#define _kCDO_Update_Source_SelectPFI10 21
#define _kCDO_Update_Source_SelectPFI11 22
#define _kCDO_Update_Source_SelectPFI12 23
#define _kCDO_Update_Source_SelectPFI13 24
#define _kCDO_Update_Source_SelectPFI14 25
#define _kCDO_Update_Source_SelectPFI15 26
#define _kCDO_Update_Source_SelectRTSI7 27
#define _kCDO_Update_Source_SelectG0_Out 28
#define _kCDO_Update_Source_SelectG1_Out 29
#define _kCDO_Update_Source_SelectAnalog_Trigger 30
#define _kCDO_Update_Source_SelectAO_Update 31
#define _kCDO_Update_Source_SelectFreq_Out 32
#define _kCDO_Update_Source_SelectDIO_Change_Detect_Irq 33
#define _kCDO_PolarityRising 0
#define _kCDO_PolarityFalling 1
#define _kCDO_FIFO_ModeFIFO_Not_Full 0
#define _kCDO_FIFO_ModeFIFO_Half_Full 1
#define _kCDO_Data_LaneCDIO_15_0 0
#define _kCDO_Data_LaneCDIO_31_16 1
#define _kCDO_Data_LaneCDIO_7_0 0
#define _kCDO_Data_LaneCDIO_15_8 1
#define _kCDO_Data_LaneCDIO_23_16 2
#define _kCDO_Data_LaneCDIO_31_24 3
         
#define _kSCXI_Force_AI_EXTMUX_CLK_Width 1
#define _kSCXI_Force_AI_EXTMUX_CLK_Width250ns 0
#define _kSCXI_Force_AI_EXTMUX_CLK_Width500ns 1
         
#define _kValue0 1
#define _kValue1 3
         
#define _kAO_DAC_Offset_Select 1
#define _kAO_DAC_Reference_Select 2
#define _kAO_Update_Mode 3
#define _kAO_DAC_Polarity 4
#define _kAO_Update_ModeImmediate 0
#define _kAO_Update_ModeTimed 1
#define _kAO_DAC_PolarityUnipolar 0
#define _kAO_DAC_PolarityBipolar 1
         
#define _kLow_Time 1
#define _kHigh_Time 2
         
#define _kAO_Waveform_OrderArraySize 16
#define _kAO_Config_BankArraySize 4
#define _kDAC_Direct_DataArraySize 16
#define _kGen_PWMArraySize 7
#define _kStatic_AI_ControlArraySize 8
#define _kAI_Command_1 0
#define _kAI_Command_2 1
#define _kAI_Mode_2 2
#define _kAI_Mode_3 3
#define _kAI_Personal 4
#define _kAI_Output_Control 5
#define _kAI_SC_Load_A 6
#define _kAI_SC_Load_B 7
#define _kAI_SC_Save 8
#define _kAI_SI_Load_A 9
#define _kAI_SI_Load_B 10
#define _kAI_SI_Save 11
#define _kAI_SI2_Load_A 12
#define _kAI_SI2_Load_B 13
#define _kAI_START_STOP_Select 14
#define _kAI_Status_1 15
#define _kAnalog_Trigger_Etc 16
#define _kAI_Trigger_Select 17
#define _kAO_BC_Load_A 18
#define _kAO_BC_Load_B 19
#define _kAO_BC_Save 20
#define _kAO_Command_2 21
#define _kAO_Command_1 22
#define _kAO_Mode_1 23
#define _kAO_Mode_2 24
#define _kAO_Output_Control 25
#define _kAO_Mode_3 26
#define _kAO_Personal 27
#define _kAO_START_Select 28
#define _kAO_Status_2 29
#define _kAO_Status_1 30
#define _kAO_Trigger_Select 31
#define _kAO_UC_Load_A 32
#define _kAO_UC_Load_B 33
#define _kAO_UC_Save 34
#define _kAO_UI_Load_A 35
#define _kAO_UI_Load_B 36
#define _kAO_UI_Save 37
#define _kClock_and_FOUT 38
#define _kInterrupt_A_Ack 39
#define _kInterrupt_A_Enable 40
#define _kInterrupt_B_Ack 41
#define _kInterrupt_Control 42
#define _kInterrupt_B_Enable 43
#define _kIO_Bidirection_Pin 44
#define _kJoint_Reset 45
#define _kJoint_Status_2 46
#define _kJoint_Status_1 47
#define _kRTSI_Shared_MUX 48
#define _kRTSI_Trig_A_Output 49
#define _kRTSI_Trig_Direction 50
#define _kRTSI_Trig_B_Output 51
#define _kG0_DMA_Config 52
#define _kG1_DMA_Config 53
#define _kG0_DMA_Status 54
#define _kG1_DMA_Status 55
#define _kCDIO_DMA_Select 56
#define _kSCXI_Control 57
#define _kAI_Mode_1 58
#define _kAI_DIV_Load_A 59
#define _kSCXI_Serial_Data_In 60
#define _kSCXI_Serial_Data_Out 61
#define _kSCXI_Status 62
#define _kSCXI_Output_Enable 63
#define _kSCXI_DIO_Enable 64
#define _kStatic_Digital_Output 65
#define _kStatic_Digital_Input 66
#define _kDIO_Direction 67
#define _kAO_Serial_Interrupt_Enable 68
#define _kAO_Serial_Interrupt_Ack 69
#define _kAO_Serial_Interrupt_Status 70
#define _kInterrupt_C_Enable 71
#define _kInterrupt_C_Status 72
#define _kAnalog_Trigger_Control 73
#define _kAI_FIFO_Data 74
#define _kAI_FIFO_Clear 75
#define _kAI_AO_Select 76
#define _kAI_Config_FIFO_Data 77
#define _kConfiguration_Memory_Clear 78
#define _kAO_FIFO_Data 79
#define _kAO_FIFO_Clear 80
#define _kG0_G1_Select 81
#define _kMisc_Command 82
#define _kAO_Calibration 83
#define _kPFI_Output_Select_1 84
#define _kPFI_Output_Select_2 85
#define _kPFI_Output_Select_3 86
#define _kPFI_Output_Select_4 87
#define _kPFI_Output_Select_5 88
#define _kPFI_Output_Select_6 89
#define _kPFI_DI 90
#define _kPFI_DO 91
#define _kPFI_Filter 92
#define _kRTSI_Filter 93
#define _kClock_And_Fout2 94
#define _kPLL_Control 95
#define _kPLL_Status 96
#define _kAI_Config_FIFO_Bypass 97
#define _kCDI_FIFO_Data 98
#define _kCDO_FIFO_Data 99
#define _kCDIO_Status 100
#define _kCDIO_Command 101
#define _kCDI_Mode 102
#define _kCDO_Mode 103
#define _kCDI_Mask_Enable 104
#define _kCDO_Mask_Enable 105
#define _kSCXI_Legacy_Compatibility 106
#define _kDIO_Reserved_0 107
#define _kDIO_Reserved_1 108
#define _kDIO_Reserved_2 109
#define _kDIO_Reserved_3 110
#define _kDIO_Reserved_4 111
#define _kDIO_Reserved_5 112
#define _kDIO_Reserved_6 113
#define _kDIO_Reserved_7 114
#define _kLB_Reserved_0 115
#define _kLB_Reserved_1 116
#define _kAO_Waveform_Order0 117
#define _kAO_Waveform_Order1 118
#define _kAO_Waveform_Order2 119
#define _kAO_Waveform_Order3 120
#define _kAO_Waveform_Order4 121
#define _kAO_Waveform_Order5 122
#define _kAO_Waveform_Order6 123
#define _kAO_Waveform_Order7 124
#define _kAO_Waveform_Order8 125
#define _kAO_Waveform_Order9 126
#define _kAO_Waveform_Order10 127
#define _kAO_Waveform_Order11 128
#define _kAO_Waveform_Order12 129
#define _kAO_Waveform_Order13 130
#define _kAO_Waveform_Order14 131
#define _kAO_Waveform_Order15 132
#define _kAO_Config_Bank0 133
#define _kAO_Config_Bank1 134
#define _kAO_Config_Bank2 135
#define _kAO_Config_Bank3 136
#define _kDAC0_Direct_Data 137
#define _kDAC1_Direct_Data 138
#define _kDAC2_Direct_Data 139
#define _kDAC3_Direct_Data 140
#define _kDAC4_Direct_Data 141
#define _kDAC5_Direct_Data 142
#define _kDAC6_Direct_Data 143
#define _kDAC7_Direct_Data 144
#define _kDAC8_Direct_Data 145
#define _kDAC9_Direct_Data 146
#define _kDAC10_Direct_Data 147
#define _kDAC11_Direct_Data 148
#define _kDAC12_Direct_Data 149
#define _kDAC13_Direct_Data 150
#define _kDAC14_Direct_Data 151
#define _kDAC15_Direct_Data 152
#define _kCal_PWM 153
#define _kGen_PWM0 154
#define _kGen_PWM1 155
#define _kGen_PWM2 156
#define _kGen_PWM3 157
#define _kGen_PWM4 158
#define _kGen_PWM5 159
#define _kGen_PWM6 160
#define _kStatic_AI_Control0 161
#define _kStatic_AI_Control1 162
#define _kStatic_AI_Control2 163
#define _kStatic_AI_Control3 164
#define _kStatic_AI_Control4 165
#define _kStatic_AI_Control5 166
#define _kStatic_AI_Control6 167
#define _kStatic_AI_Control7 168
#define _kMaxRegister 168
